# Install script for directory: /Users/kevinq/Downloads/parabix-devel

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/codegen/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/fileselect/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/grep/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/idisa/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/kernel/core/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/kernel/pipeline/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/objcache/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/pablo/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/pablo/bixnum/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/pablo/parse/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/re/adt/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/re/alphabet/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/re/analysis/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/re/cc/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/re/compile/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/re/parse/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/re/toolchain/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/re/transforms/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/re/ucd/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/re/unicode/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/testing/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/toolchain/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/unicode/core/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/unicode/data/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/unicode/utf/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/kernel/basis/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/kernel/io/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/kernel/scan/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/kernel/streamutils/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/kernel/unicode/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/lib/kernel/util/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/tools/base64/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/tools/editd/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/tools/icgrep/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/tools/idisa_test/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/tools/transcoders/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/tools/wc/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/tools/xml/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/tools/ztf8/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/tools/util/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/tools/pinyin_grep/cmake_install.cmake")
  include("/Users/kevinq/Downloads/parabix-devel/pinyin_grep/tests/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "/Users/kevinq/Downloads/parabix-devel/pinyin_grep/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
