# CMake generated Testfile for 
# Source directory: /Users/kevinq/Downloads/parabix-devel
# Build directory: /Users/kevinq/Downloads/parabix-devel/pinyin_grep
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(pinyin_test "python" "../greptest.py" "-v" "-d" "/Users/kevinq/Downloads/parabix-devel/QA/pinyin_test/testfiles" "-t" "/Users/kevinq/Downloads/parabix-devel/QA/pinyin_test/pinyin_test.xml" "/Users/kevinq/Downloads/parabix-devel/pinyin_grep/bin/pinyin_grep")
set_tests_properties(pinyin_test PROPERTIES  WORKING_DIRECTORY "/Users/kevinq/Downloads/parabix-devel/QA/pinyin_test" _BACKTRACE_TRIPLES "/Users/kevinq/Downloads/parabix-devel/CMakeLists.txt;358;add_test;/Users/kevinq/Downloads/parabix-devel/CMakeLists.txt;0;")
add_test(greptest "python" "greptest.py" "--random_flag_count=2" "--tests_per_grepcase=2" "/Users/kevinq/Downloads/parabix-devel/pinyin_grep/bin/icgrep")
set_tests_properties(greptest PROPERTIES  WORKING_DIRECTORY "/Users/kevinq/Downloads/parabix-devel/QA" _BACKTRACE_TRIPLES "/Users/kevinq/Downloads/parabix-devel/CMakeLists.txt;363;add_test;/Users/kevinq/Downloads/parabix-devel/CMakeLists.txt;0;")
add_test(proptest "python" "greptest.py" "-d" "/Users/kevinq/Downloads/parabix-devel/QA" "-t" "/Users/kevinq/Downloads/parabix-devel/QA/proptest.xml" "/Users/kevinq/Downloads/parabix-devel/pinyin_grep/bin/icgrep")
set_tests_properties(proptest PROPERTIES  TIMEOUT "1500" WORKING_DIRECTORY "/Users/kevinq/Downloads/parabix-devel/QA" _BACKTRACE_TRIPLES "/Users/kevinq/Downloads/parabix-devel/CMakeLists.txt;368;add_test;/Users/kevinq/Downloads/parabix-devel/CMakeLists.txt;0;")
add_test(abc_test "./run_abc" "/Users/kevinq/Downloads/parabix-devel/pinyin_grep/bin/icgrep")
set_tests_properties(abc_test PROPERTIES  TIMEOUT "100" WORKING_DIRECTORY "/Users/kevinq/Downloads/parabix-devel/QA" _BACKTRACE_TRIPLES "/Users/kevinq/Downloads/parabix-devel/CMakeLists.txt;379;add_test;/Users/kevinq/Downloads/parabix-devel/CMakeLists.txt;0;")
add_test(u8u16_test "./run_all" "/Users/kevinq/Downloads/parabix-devel/pinyin_grep/bin/u8u16 -thread-num=2")
set_tests_properties(u8u16_test PROPERTIES  TIMEOUT "40" WORKING_DIRECTORY "/Users/kevinq/Downloads/parabix-devel/QA/u8u16" _BACKTRACE_TRIPLES "/Users/kevinq/Downloads/parabix-devel/CMakeLists.txt;384;add_test;/Users/kevinq/Downloads/parabix-devel/CMakeLists.txt;0;")
add_test(u32u8_test "./test_u32u8" "/Users/kevinq/Downloads/parabix-devel/pinyin_grep/bin/u32u8")
set_tests_properties(u32u8_test PROPERTIES  WORKING_DIRECTORY "/Users/kevinq/Downloads/parabix-devel/QA/" _BACKTRACE_TRIPLES "/Users/kevinq/Downloads/parabix-devel/CMakeLists.txt;389;add_test;/Users/kevinq/Downloads/parabix-devel/CMakeLists.txt;0;")
add_test(editd_test "python" "run_all.py" "-e" "/Users/kevinq/Downloads/parabix-devel/pinyin_grep/bin")
set_tests_properties(editd_test PROPERTIES  TIMEOUT "40" WORKING_DIRECTORY "/Users/kevinq/Downloads/parabix-devel/QA/editd" _BACKTRACE_TRIPLES "/Users/kevinq/Downloads/parabix-devel/CMakeLists.txt;394;add_test;/Users/kevinq/Downloads/parabix-devel/CMakeLists.txt;0;")
add_test(base64_test "python" "base64test.py" "/Users/kevinq/Downloads/parabix-devel/pinyin_grep/bin/base64")
set_tests_properties(base64_test PROPERTIES  TIMEOUT "40" WORKING_DIRECTORY "/Users/kevinq/Downloads/parabix-devel/QA/base64" _BACKTRACE_TRIPLES "/Users/kevinq/Downloads/parabix-devel/CMakeLists.txt;399;add_test;/Users/kevinq/Downloads/parabix-devel/CMakeLists.txt;0;")
subdirs("lib/codegen")
subdirs("lib/fileselect")
subdirs("lib/grep")
subdirs("lib/idisa")
subdirs("lib/kernel/core")
subdirs("lib/kernel/pipeline")
subdirs("lib/objcache")
subdirs("lib/pablo")
subdirs("lib/pablo/bixnum")
subdirs("lib/pablo/parse")
subdirs("lib/re/adt")
subdirs("lib/re/alphabet")
subdirs("lib/re/analysis")
subdirs("lib/re/cc")
subdirs("lib/re/compile")
subdirs("lib/re/parse")
subdirs("lib/re/toolchain")
subdirs("lib/re/transforms")
subdirs("lib/re/ucd")
subdirs("lib/re/unicode")
subdirs("lib/testing")
subdirs("lib/toolchain")
subdirs("lib/unicode/core")
subdirs("lib/unicode/data")
subdirs("lib/unicode/utf")
subdirs("lib/kernel/basis")
subdirs("lib/kernel/io")
subdirs("lib/kernel/scan")
subdirs("lib/kernel/streamutils")
subdirs("lib/kernel/unicode")
subdirs("lib/kernel/util")
subdirs("tools/base64")
subdirs("tools/editd")
subdirs("tools/icgrep")
subdirs("tools/idisa_test")
subdirs("tools/transcoders")
subdirs("tools/wc")
subdirs("tools/xml")
subdirs("tools/ztf8")
subdirs("tools/util")
subdirs("tools/pinyin_grep")
subdirs("tests")
