#ifndef PROPERTYOBJECTTABLE_H
#define PROPERTYOBJECTTABLE_H
/*
 *  Copyright (c) 2014 International Characters, Inc.
 *  This software is licensed to the public under the Open Software License 3.0.
 *  icgrep is a trademark of International Characters, Inc.
 *
 *  This file is generated by UCD_properties.y - manual edits may be lost.
 */

#include "PropertyObjects.h"
#include "PropertyAliases.h"
#include "Blocks.h"
#include "Scripts.h"
#include "DerivedGeneralCategory.h"
#include "PropList.h"
#include "DerivedCoreProperties.h"
#include "LineBreak.h"
#include "EastAsianWidth.h"
#include "HangulSyllableType.h"

namespace UCD {

  const PropertyObject* property_object_table[] = {
    new UnsupportedPropertyObject(cjkaccountingnumeric, NumericProperty),
    new UnsupportedPropertyObject(cjkothernumeric, NumericProperty),
    new UnsupportedPropertyObject(cjkprimarynumeric, NumericProperty),
    new UnsupportedPropertyObject(nv, NumericProperty),
    new UnsupportedPropertyObject(cf, StringProperty),
    new UnsupportedPropertyObject(cjkcompatibilityvariant, StringProperty),
    new UnsupportedPropertyObject(dm, StringProperty),
    new UnsupportedPropertyObject(fc_nfkc, StringProperty),
    new UnsupportedPropertyObject(lc, StringProperty),
    new UnsupportedPropertyObject(nfkc_cf, StringProperty),
    new UnsupportedPropertyObject(scf, CodepointProperty),
    new UnsupportedPropertyObject(slc, CodepointProperty),
    new UnsupportedPropertyObject(stc, CodepointProperty),
    new UnsupportedPropertyObject(suc, CodepointProperty),
    new UnsupportedPropertyObject(tc, StringProperty),
    new UnsupportedPropertyObject(uc, StringProperty),
    new UnsupportedPropertyObject(bmg, MiscellaneousProperty),
    new UnsupportedPropertyObject(bpb, MiscellaneousProperty),
    new UnsupportedPropertyObject(cjkiicore, MiscellaneousProperty),
    new UnsupportedPropertyObject(cjkirg_gsource, MiscellaneousProperty),
    new UnsupportedPropertyObject(cjkirg_hsource, MiscellaneousProperty),
    new UnsupportedPropertyObject(cjkirg_jsource, MiscellaneousProperty),
    new UnsupportedPropertyObject(cjkirg_kpsource, MiscellaneousProperty),
    new UnsupportedPropertyObject(cjkirg_ksource, MiscellaneousProperty),
    new UnsupportedPropertyObject(cjkirg_msource, MiscellaneousProperty),
    new UnsupportedPropertyObject(cjkirg_tsource, MiscellaneousProperty),
    new UnsupportedPropertyObject(cjkirg_usource, MiscellaneousProperty),
    new UnsupportedPropertyObject(cjkirg_vsource, MiscellaneousProperty),
    new UnsupportedPropertyObject(cjkrsunicode, MiscellaneousProperty),
    new UnsupportedPropertyObject(isc, MiscellaneousProperty),
    new UnsupportedPropertyObject(jsn, MiscellaneousProperty),
    new UnsupportedPropertyObject(na, MiscellaneousProperty),
    new UnsupportedPropertyObject(na1, MiscellaneousProperty),
    new UnsupportedPropertyObject(name_alias, MiscellaneousProperty),
    new UnsupportedPropertyObject(scx, MiscellaneousProperty),
    new UnsupportedPropertyObject(age, CatalogProperty),
    &BLK::property_object,
    &SC::property_object,
    new UnsupportedPropertyObject(bc, EnumeratedProperty),
    new UnsupportedPropertyObject(bpt, EnumeratedProperty),
    new UnsupportedPropertyObject(ccc, EnumeratedProperty),
    new UnsupportedPropertyObject(dt, EnumeratedProperty),
    &EA::property_object,
    &GC::property_object,
    new UnsupportedPropertyObject(gcb, EnumeratedProperty),
    &HST::property_object,
    new UnsupportedPropertyObject(inmc, EnumeratedProperty),
    new UnsupportedPropertyObject(insc, EnumeratedProperty),
    new UnsupportedPropertyObject(jg, EnumeratedProperty),
    new UnsupportedPropertyObject(jt, EnumeratedProperty),
    &LB::property_object,
    new UnsupportedPropertyObject(nfc_qc, EnumeratedProperty),
    new UnsupportedPropertyObject(nfd_qc, EnumeratedProperty),
    new UnsupportedPropertyObject(nfkc_qc, EnumeratedProperty),
    new UnsupportedPropertyObject(nfkd_qc, EnumeratedProperty),
    new UnsupportedPropertyObject(nt, EnumeratedProperty),
    new UnsupportedPropertyObject(sb, EnumeratedProperty),
    new UnsupportedPropertyObject(wb, EnumeratedProperty),
    &AHEX::property_object,
    &ALPHA::property_object,
    &BIDI_C::property_object,
    new UnsupportedPropertyObject(bidi_m, BinaryProperty),
    &CASED::property_object,
    new UnsupportedPropertyObject(ce, BinaryProperty),
    &CI::property_object,
    new UnsupportedPropertyObject(comp_ex, BinaryProperty),
    &CWCF::property_object,
    &CWCM::property_object,
    new UnsupportedPropertyObject(cwkcf, BinaryProperty),
    &CWL::property_object,
    &CWT::property_object,
    &CWU::property_object,
    &DASH::property_object,
    &DEP::property_object,
    &DI::property_object,
    &DIA::property_object,
    &EXT::property_object,
    &GR_BASE::property_object,
    &GR_EXT::property_object,
    &GR_LINK::property_object,
    &HEX::property_object,
    &HYPHEN::property_object,
    &IDC::property_object,
    &IDEO::property_object,
    &IDS::property_object,
    &IDSB::property_object,
    &IDST::property_object,
    &JOIN_C::property_object,
    &LOE::property_object,
    &LOWER::property_object,
    &MATH::property_object,
    &NCHAR::property_object,
    &OALPHA::property_object,
    &ODI::property_object,
    &OGR_EXT::property_object,
    &OIDC::property_object,
    &OIDS::property_object,
    &OLOWER::property_object,
    &OMATH::property_object,
    &OUPPER::property_object,
    &PAT_SYN::property_object,
    &PAT_WS::property_object,
    &QMARK::property_object,
    &RADICAL::property_object,
    &SD::property_object,
    &STERM::property_object,
    &TERM::property_object,
    &UIDEO::property_object,
    &UPPER::property_object,
    &VS::property_object,
    &WSPACE::property_object,
    &XIDC::property_object,
    &XIDS::property_object,
    new UnsupportedPropertyObject(xo_nfc, BinaryProperty),
    new UnsupportedPropertyObject(xo_nfd, BinaryProperty),
    new UnsupportedPropertyObject(xo_nfkc, BinaryProperty),
    new UnsupportedPropertyObject(xo_nfkd, BinaryProperty)  };
}

#endif
