#ifndef PROPERTYOBJECTTABLE_H
#define PROPERTYOBJECTTABLE_H
/*
 *  Copyright (c) 2015 International Characters, Inc.
 *  This software is licensed to the public under the Open Software License 3.0.
 *  icgrep is a trademark of International Characters, Inc.
 *
 *  This file is generated by UCD_properties.py - manual edits may be lost.
 */

#include "PropertyObjects.h"
#include "PropertyAliases.h"
#include <array>
#include "Blocks.h"
#include "Scripts.h"
#include "ScriptExtensions.h"
#include "DerivedGeneralCategory.h"
#include "PropList.h"
#include "DerivedCoreProperties.h"
#include "LineBreak.h"
#include "EastAsianWidth.h"
#include "HangulSyllableType.h"

namespace UCD {

  const std::array<PropertyObject *, 117> property_object_table = {{
    new UnsupportedPropertyObject(cjkAccountingNumeric, PropertyObject::ClassTypeId::NumericProperty),
    new UnsupportedPropertyObject(cjkOtherNumeric, PropertyObject::ClassTypeId::NumericProperty),
    new UnsupportedPropertyObject(cjkPrimaryNumeric, PropertyObject::ClassTypeId::NumericProperty),
    new UnsupportedPropertyObject(nv, PropertyObject::ClassTypeId::NumericProperty),
    new UnsupportedPropertyObject(cf, PropertyObject::ClassTypeId::StringProperty),
    new UnsupportedPropertyObject(cjkCompatibilityVariant, PropertyObject::ClassTypeId::StringProperty),
    new UnsupportedPropertyObject(dm, PropertyObject::ClassTypeId::StringProperty),
    new UnsupportedPropertyObject(FC_NFKC, PropertyObject::ClassTypeId::StringProperty),
    new UnsupportedPropertyObject(lc, PropertyObject::ClassTypeId::StringProperty),
    new UnsupportedPropertyObject(NFKC_CF, PropertyObject::ClassTypeId::StringProperty),
    new UnsupportedPropertyObject(scf, PropertyObject::ClassTypeId::CodepointProperty),
    new UnsupportedPropertyObject(slc, PropertyObject::ClassTypeId::CodepointProperty),
    new UnsupportedPropertyObject(stc, PropertyObject::ClassTypeId::CodepointProperty),
    new UnsupportedPropertyObject(suc, PropertyObject::ClassTypeId::CodepointProperty),
    new UnsupportedPropertyObject(tc, PropertyObject::ClassTypeId::StringProperty),
    new UnsupportedPropertyObject(uc, PropertyObject::ClassTypeId::StringProperty),
    new UnsupportedPropertyObject(bmg, PropertyObject::ClassTypeId::MiscellaneousProperty),
    new UnsupportedPropertyObject(bpb, PropertyObject::ClassTypeId::MiscellaneousProperty),
    new UnsupportedPropertyObject(cjkIICore, PropertyObject::ClassTypeId::MiscellaneousProperty),
    new UnsupportedPropertyObject(cjkIRG_GSource, PropertyObject::ClassTypeId::MiscellaneousProperty),
    new UnsupportedPropertyObject(cjkIRG_HSource, PropertyObject::ClassTypeId::MiscellaneousProperty),
    new UnsupportedPropertyObject(cjkIRG_JSource, PropertyObject::ClassTypeId::MiscellaneousProperty),
    new UnsupportedPropertyObject(cjkIRG_KPSource, PropertyObject::ClassTypeId::MiscellaneousProperty),
    new UnsupportedPropertyObject(cjkIRG_KSource, PropertyObject::ClassTypeId::MiscellaneousProperty),
    new UnsupportedPropertyObject(cjkIRG_MSource, PropertyObject::ClassTypeId::MiscellaneousProperty),
    new UnsupportedPropertyObject(cjkIRG_TSource, PropertyObject::ClassTypeId::MiscellaneousProperty),
    new UnsupportedPropertyObject(cjkIRG_USource, PropertyObject::ClassTypeId::MiscellaneousProperty),
    new UnsupportedPropertyObject(cjkIRG_VSource, PropertyObject::ClassTypeId::MiscellaneousProperty),
    new UnsupportedPropertyObject(cjkRSUnicode, PropertyObject::ClassTypeId::MiscellaneousProperty),
    new UnsupportedPropertyObject(isc, PropertyObject::ClassTypeId::MiscellaneousProperty),
    new UnsupportedPropertyObject(JSN, PropertyObject::ClassTypeId::MiscellaneousProperty),
    new UnsupportedPropertyObject(na, PropertyObject::ClassTypeId::MiscellaneousProperty),
    new UnsupportedPropertyObject(na1, PropertyObject::ClassTypeId::MiscellaneousProperty),
    new UnsupportedPropertyObject(Name_Alias, PropertyObject::ClassTypeId::MiscellaneousProperty),
    new UnsupportedPropertyObject(scx, PropertyObject::ClassTypeId::MiscellaneousProperty),
    new UnsupportedPropertyObject(age, PropertyObject::ClassTypeId::CatalogProperty),
    &BLK_ns::property_object,
    &SC_ns::property_object,
    new UnsupportedPropertyObject(bc, PropertyObject::ClassTypeId::EnumeratedProperty),
    new UnsupportedPropertyObject(bpt, PropertyObject::ClassTypeId::EnumeratedProperty),
    new UnsupportedPropertyObject(ccc, PropertyObject::ClassTypeId::EnumeratedProperty),
    new UnsupportedPropertyObject(dt, PropertyObject::ClassTypeId::EnumeratedProperty),
    &EA_ns::property_object,
    &GC_ns::property_object,
    new UnsupportedPropertyObject(GCB, PropertyObject::ClassTypeId::EnumeratedProperty),
    &HST_ns::property_object,
    new UnsupportedPropertyObject(InMC, PropertyObject::ClassTypeId::EnumeratedProperty),
    new UnsupportedPropertyObject(InSC, PropertyObject::ClassTypeId::EnumeratedProperty),
    new UnsupportedPropertyObject(jg, PropertyObject::ClassTypeId::EnumeratedProperty),
    new UnsupportedPropertyObject(jt, PropertyObject::ClassTypeId::EnumeratedProperty),
    &LB_ns::property_object,
    new UnsupportedPropertyObject(NFC_QC, PropertyObject::ClassTypeId::EnumeratedProperty),
    new UnsupportedPropertyObject(NFD_QC, PropertyObject::ClassTypeId::EnumeratedProperty),
    new UnsupportedPropertyObject(NFKC_QC, PropertyObject::ClassTypeId::EnumeratedProperty),
    new UnsupportedPropertyObject(NFKD_QC, PropertyObject::ClassTypeId::EnumeratedProperty),
    new UnsupportedPropertyObject(nt, PropertyObject::ClassTypeId::EnumeratedProperty),
    new UnsupportedPropertyObject(SB, PropertyObject::ClassTypeId::EnumeratedProperty),
    new UnsupportedPropertyObject(WB, PropertyObject::ClassTypeId::EnumeratedProperty),
    &AHEX_ns::property_object,
    &ALPHA_ns::property_object,
    &BIDI_C_ns::property_object,
    new UnsupportedPropertyObject(Bidi_M, PropertyObject::ClassTypeId::BinaryProperty),
    &CASED_ns::property_object,
    new UnsupportedPropertyObject(CE, PropertyObject::ClassTypeId::BinaryProperty),
    &CI_ns::property_object,
    new UnsupportedPropertyObject(Comp_Ex, PropertyObject::ClassTypeId::BinaryProperty),
    &CWCF_ns::property_object,
    &CWCM_ns::property_object,
    new UnsupportedPropertyObject(CWKCF, PropertyObject::ClassTypeId::BinaryProperty),
    &CWL_ns::property_object,
    &CWT_ns::property_object,
    &CWU_ns::property_object,
    &DASH_ns::property_object,
    &DEP_ns::property_object,
    &DI_ns::property_object,
    &DIA_ns::property_object,
    &EXT_ns::property_object,
    &GR_BASE_ns::property_object,
    &GR_EXT_ns::property_object,
    &GR_LINK_ns::property_object,
    &HEX_ns::property_object,
    &HYPHEN_ns::property_object,
    &IDC_ns::property_object,
    &IDEO_ns::property_object,
    &IDS_ns::property_object,
    &IDSB_ns::property_object,
    &IDST_ns::property_object,
    &JOIN_C_ns::property_object,
    &LOE_ns::property_object,
    &LOWER_ns::property_object,
    &MATH_ns::property_object,
    &NCHAR_ns::property_object,
    &OALPHA_ns::property_object,
    &ODI_ns::property_object,
    &OGR_EXT_ns::property_object,
    &OIDC_ns::property_object,
    &OIDS_ns::property_object,
    &OLOWER_ns::property_object,
    &OMATH_ns::property_object,
    &OUPPER_ns::property_object,
    &PAT_SYN_ns::property_object,
    &PAT_WS_ns::property_object,
    &QMARK_ns::property_object,
    &RADICAL_ns::property_object,
    &SD_ns::property_object,
    &STERM_ns::property_object,
    &TERM_ns::property_object,
    &UIDEO_ns::property_object,
    &UPPER_ns::property_object,
    &VS_ns::property_object,
    &WSPACE_ns::property_object,
    &XIDC_ns::property_object,
    &XIDS_ns::property_object,
    new UnsupportedPropertyObject(XO_NFC, PropertyObject::ClassTypeId::BinaryProperty),
    new UnsupportedPropertyObject(XO_NFD, PropertyObject::ClassTypeId::BinaryProperty),
    new UnsupportedPropertyObject(XO_NFKC, PropertyObject::ClassTypeId::BinaryProperty),
    new UnsupportedPropertyObject(XO_NFKD, PropertyObject::ClassTypeId::BinaryProperty)  }};
}

#endif
