#ifndef SCRIPTEXTENSIONS_H
#define SCRIPTEXTENSIONS_H
/*
 *  Copyright (c) 2015 International Characters, Inc.
 *  This software is licensed to the public under the Open Software License 3.0.
 *  icgrep is a trademark of International Characters, Inc.
 *
 *  This file is generated by UCD_properties.py - manual edits may be lost.
 */

#include "PropertyObjects.h"
#include "PropertyValueAliases.h"
#include "unicode_set.h"

namespace UCD {
    namespace SCX_ns {
        /** Code Point Ranges for Aghb
        [66864, 66915], [66927, 66927]**/
        const UnicodeSet aghb_Ext 
            {{{Empty, 2089}, {Mixed, 1}, {Full, 1}, {Mixed, 1},
              {Empty, 32724}},
             {0xffff0000, 0x0000800f}};
        /** Code Point Ranges for Ahom
        [71424, 71449], [71453, 71467], [71472, 71487]**/
        const UnicodeSet ahom_Ext 
            {{{Empty, 2232}, {Mixed, 2}, {Empty, 32582}},
             {0xe3ffffff, 0xffff0fff}};
        /** Code Point Ranges for Arab
        [1536, 1540], [1542, 1563], [1566, 1756], [1758, 1791],
        [1872, 1919], [2208, 2228], [2275, 2303], [64336, 64449],
        [64467, 64829], [64848, 64911], [64914, 64967], [65008, 65021],
        [65136, 65140], [65142, 65276], [66272, 66299], [69216, 69246],
        [126464, 126467], [126469, 126495], [126497, 126498],
        [126500, 126500], [126503, 126503], [126505, 126514],
        [126516, 126519], [126521, 126521], [126523, 126523],
        [126530, 126530], [126535, 126535], [126537, 126537],
        [126539, 126539], [126541, 126543], [126545, 126546],
        [126548, 126548], [126551, 126551], [126553, 126553],
        [126555, 126555], [126557, 126557], [126559, 126559],
        [126561, 126562], [126564, 126564], [126567, 126570],
        [126572, 126578], [126580, 126583], [126585, 126588],
        [126590, 126590], [126592, 126601], [126603, 126619],
        [126625, 126627], [126629, 126633], [126635, 126651],
        [126704, 126705]**/
        const UnicodeSet arab_Ext 
            {{{Empty, 48}, {Mixed, 1}, {Full, 5}, {Mixed, 1}, {Full, 1},
              {Empty, 2}, {Mixed, 1}, {Full, 1}, {Empty, 9}, {Mixed, 1},
              {Empty, 1}, {Mixed, 1}, {Empty, 1938}, {Mixed, 1}, {Full, 3},
              {Mixed, 1}, {Full, 10}, {Mixed, 2}, {Full, 1}, {Mixed, 1},
              {Full, 1}, {Mixed, 2}, {Empty, 3}, {Mixed, 1}, {Full, 3},
              {Mixed, 1}, {Empty, 31}, {Mixed, 1}, {Empty, 91}, {Mixed, 1},
              {Empty, 1788}, {Mixed, 6}, {Empty, 1}, {Mixed, 1},
              {Empty, 30856}},
             {0xcfffffdf, 0xdfffffff, 0xffff0000, 0x001fffff, 0xfffffff8,
              0xffff0000, 0xfff80003, 0x3fffffff, 0xffff0000, 0xfffcffff,
              0x000000ff, 0x3fff0000, 0xffdf0000, 0x1fffffff, 0x0fffffff,
              0x7fffffff, 0xffffffef, 0x0af7fe96, 0xaa96ea84, 0x5ef7f796,
              0x0ffffbff, 0x0ffffbee, 0x00030000}};
        /** Code Point Ranges for Armi
        [67648, 67669], [67671, 67679]**/
        const UnicodeSet armi_Ext 
            {{{Empty, 2114}, {Mixed, 1}, {Empty, 32701}},
             {0xffbfffff}};
        /** Code Point Ranges for Armn
        [1329, 1366], [1369, 1375], [1377, 1415], [1417, 1418],
        [1421, 1423], [64275, 64279]**/
        const UnicodeSet armn_Ext 
            {{{Empty, 41}, {Mixed, 4}, {Empty, 1963}, {Mixed, 1},
              {Empty, 32807}},
             {0xfffe0000, 0xfe7fffff, 0xfffffffe, 0x0000e6ff, 0x00f80000}};
        /** Code Point Ranges for Avst
        [68352, 68405], [68409, 68415]**/
        const UnicodeSet avst_Ext 
            {{{Empty, 2136}, {Full, 1}, {Mixed, 1}, {Empty, 32678}},
             {0xfe3fffff}};
        /** Code Point Ranges for Bali
        [6912, 6987], [6992, 7036]**/
        const UnicodeSet bali_Ext 
            {{{Empty, 216}, {Full, 2}, {Mixed, 2}, {Empty, 34596}},
             {0xffff0fff, 0x1fffffff}};
        /** Code Point Ranges for Bamu
        [42656, 42743], [92160, 92728]**/
        const UnicodeSet bamu_Ext 
            {{{Empty, 1333}, {Full, 2}, {Mixed, 1}, {Empty, 1544},
              {Full, 17}, {Mixed, 1}, {Empty, 31918}},
             {0x00ffffff, 0x01ffffff}};
        /** Code Point Ranges for Bass
        [92880, 92909], [92912, 92917]**/
        const UnicodeSet bass_Ext 
            {{{Empty, 2902}, {Mixed, 2}, {Empty, 31912}},
             {0xffff0000, 0x003f3fff}};
        /** Code Point Ranges for Batk
        [7104, 7155], [7164, 7167]**/
        const UnicodeSet batk_Ext 
            {{{Empty, 222}, {Full, 1}, {Mixed, 1}, {Empty, 34592}},
             {0xf00fffff}};
        /** Code Point Ranges for Beng
        [2385, 2386], [2404, 2405], [2432, 2435], [2437, 2444],
        [2447, 2448], [2451, 2472], [2474, 2480], [2482, 2482],
        [2486, 2489], [2492, 2500], [2503, 2504], [2507, 2510],
        [2519, 2519], [2524, 2525], [2527, 2531], [2534, 2555]**/
        const UnicodeSet beng_Ext 
            {{{Empty, 74}, {Mixed, 6}, {Empty, 34736}},
             {0x00060000, 0x00000030, 0xfff99fef, 0xf3c5fdff, 0xb080799f,
              0x0fffffcf}};
        /** Code Point Ranges for Bopo
        [746, 747], [12289, 12291], [12296, 12305], [12307, 12319],
        [12330, 12333], [12336, 12336], [12343, 12343], [12350, 12351],
        [12539, 12539], [12549, 12589], [12704, 12730], [12736, 12771],
        [12832, 12867], [12928, 12976], [12992, 13003], [13144, 13168],
        [13179, 13183], [13280, 13310], [65093, 65094], [65377, 65381]**/
        const UnicodeSet bopo_Ext 
            {{{Empty, 23}, {Mixed, 1}, {Empty, 360}, {Mixed, 2}, {Empty, 5},
              {Mixed, 3}, {Empty, 3}, {Mixed, 1}, {Full, 1}, {Mixed, 1},
              {Empty, 1}, {Full, 1}, {Mixed, 1}, {Empty, 1}, {Full, 1},
              {Mixed, 2}, {Empty, 3}, {Mixed, 2}, {Empty, 3}, {Mixed, 1},
              {Empty, 1618}, {Mixed, 1}, {Empty, 8}, {Mixed, 1},
              {Empty, 32772}},
             {0x00000c00, 0xfffbff0e, 0xc0813c00, 0x08000000, 0xffffffe0,
              0x00003fff, 0x07ffffff, 0x0000000f, 0x0000000f, 0x0001ffff,
              0x00000fff, 0xff000000, 0xf801ffff, 0x7fffffff, 0x00000060,
              0x0000003e}};
        /** Code Point Ranges for Brah
        [69632, 69709], [69714, 69743], [69759, 69759]**/
        const UnicodeSet brah_Ext 
            {{{Empty, 2176}, {Full, 2}, {Mixed, 2}, {Empty, 32636}},
             {0xfffc3fff, 0x8000ffff}};
        /** Code Point Ranges for Brai
        [10240, 10495]**/
        const UnicodeSet brai_Ext 
            {{{Empty, 320}, {Full, 8}, {Empty, 34488}},
             {}};
        /** Code Point Ranges for Bugi
        [6656, 6683], [6686, 6687], [43471, 43471]**/
        const UnicodeSet bugi_Ext 
            {{{Empty, 208}, {Mixed, 1}, {Empty, 1149}, {Mixed, 1},
              {Empty, 33457}},
             {0xcfffffff, 0x00008000}};
        /** Code Point Ranges for Buhd
        [5941, 5942], [5952, 5971]**/
        const UnicodeSet buhd_Ext 
            {{{Empty, 185}, {Mixed, 2}, {Empty, 34629}},
             {0x00600000, 0x000fffff}};
        /** Code Point Ranges for Cakm
        [2534, 2543], [4160, 4169], [69888, 69940], [69942, 69955]**/
        const UnicodeSet cakm_Ext 
            {{{Empty, 79}, {Mixed, 1}, {Empty, 50}, {Mixed, 1},
              {Empty, 2053}, {Full, 1}, {Mixed, 2}, {Empty, 32629}},
             {0x0000ffc0, 0x000003ff, 0xffdfffff, 0x0000000f}};
        /** Code Point Ranges for Cans
        [5120, 5759], [6320, 6389]**/
        const UnicodeSet cans_Ext 
            {{{Empty, 160}, {Full, 20}, {Empty, 17}, {Mixed, 1}, {Full, 1},
              {Mixed, 1}, {Empty, 34616}},
             {0xffff0000, 0x003fffff}};
        /** Code Point Ranges for Cari
        [66208, 66256]**/
        const UnicodeSet cari_Ext 
            {{{Empty, 2069}, {Full, 1}, {Mixed, 1}, {Empty, 32745}},
             {0x0001ffff}};
        /** Code Point Ranges for Cham
        [43520, 43574], [43584, 43597], [43600, 43609], [43612, 43615]**/
        const UnicodeSet cham_Ext 
            {{{Empty, 1360}, {Full, 1}, {Mixed, 2}, {Empty, 33453}},
             {0x007fffff, 0xf3ff3fff}};
        /** Code Point Ranges for Cher
        [5024, 5109], [5112, 5117], [43888, 43967]**/
        const UnicodeSet cher_Ext 
            {{{Empty, 157}, {Full, 2}, {Mixed, 1}, {Empty, 1211},
              {Mixed, 1}, {Full, 2}, {Empty, 33442}},
             {0x3f3fffff, 0xffff0000}};
        /** Code Point Ranges for Copt
        [994, 1007], [11392, 11507], [11513, 11519], [66272, 66299]**/
        const UnicodeSet copt_Ext 
            {{{Empty, 31}, {Mixed, 1}, {Empty, 324}, {Full, 3}, {Mixed, 1},
              {Empty, 1711}, {Mixed, 1}, {Empty, 32744}},
             {0x0000fffc, 0xfe0fffff, 0x0fffffff}};
        /** Code Point Ranges for Cprt
        [65792, 65794], [65799, 65843], [65847, 65855], [67584, 67589],
        [67592, 67592], [67594, 67637], [67639, 67640], [67644, 67644],
        [67647, 67647]**/
        const UnicodeSet cprt_Ext 
            {{{Empty, 2056}, {Mixed, 2}, {Empty, 54}, {Mixed, 2},
              {Empty, 32702}},
             {0xffffff87, 0xff8fffff, 0xfffffd3f, 0x91bfffff}};
        /** Code Point Ranges for Cyrl
        [1024, 1327], [7467, 7467], [7544, 7544], [11744, 11775],
        [42560, 42655], [65070, 65071]**/
        const UnicodeSet cyrl_Ext 
            {{{Empty, 32}, {Full, 9}, {Mixed, 1}, {Empty, 191}, {Mixed, 1},
              {Empty, 1}, {Mixed, 1}, {Empty, 131}, {Full, 1}, {Empty, 962},
              {Full, 3}, {Empty, 700}, {Mixed, 1}, {Empty, 32782}},
             {0x0000ffff, 0x00000800, 0x01000000, 0x0000c000}};
        /** Code Point Ranges for Deva
        [2304, 2431], [7376, 7414], [7416, 7417], [8432, 8432],
        [43056, 43065], [43232, 43261]**/
        const UnicodeSet deva_Ext 
            {{{Empty, 72}, {Full, 4}, {Empty, 154}, {Mixed, 2}, {Empty, 31},
              {Mixed, 1}, {Empty, 1081}, {Mixed, 1}, {Empty, 5}, {Mixed, 1},
              {Empty, 33464}},
             {0xffff0000, 0x037fffff, 0x00010000, 0x03ff0000, 0x3fffffff}};
        /** Code Point Ranges for Dsrt
        [66560, 66639]**/
        const UnicodeSet dsrt_Ext 
            {{{Empty, 2080}, {Full, 2}, {Mixed, 1}, {Empty, 32733}},
             {0x0000ffff}};
        /** Code Point Ranges for Dupl
        [113664, 113770], [113776, 113788], [113792, 113800],
        [113808, 113817], [113820, 113827]**/
        const UnicodeSet dupl_Ext 
            {{{Empty, 3552}, {Full, 3}, {Mixed, 3}, {Empty, 31258}},
             {0x1fff07ff, 0xf3ff01ff, 0x0000000f}};
        /** Code Point Ranges for Egyp
        [77824, 78894]**/
        const UnicodeSet egyp_Ext 
            {{{Empty, 2432}, {Full, 33}, {Mixed, 1}, {Empty, 32350}},
             {0x00007fff}};
        /** Code Point Ranges for Elba
        [66816, 66855]**/
        const UnicodeSet elba_Ext 
            {{{Empty, 2088}, {Full, 1}, {Mixed, 1}, {Empty, 32726}},
             {0x000000ff}};
        /** Code Point Ranges for Ethi
        [4608, 4680], [4682, 4685], [4688, 4694], [4696, 4696],
        [4698, 4701], [4704, 4744], [4746, 4749], [4752, 4784],
        [4786, 4789], [4792, 4798], [4800, 4800], [4802, 4805],
        [4808, 4822], [4824, 4880], [4882, 4885], [4888, 4954],
        [4957, 4988], [4992, 5017], [11648, 11670], [11680, 11686],
        [11688, 11694], [11696, 11702], [11704, 11710], [11712, 11718],
        [11720, 11726], [11728, 11734], [11736, 11742], [43777, 43782],
        [43785, 43790], [43793, 43798], [43808, 43814], [43816, 43822]**/
        const UnicodeSet ethi_Ext 
            {{{Empty, 144}, {Full, 2}, {Mixed, 1}, {Full, 1}, {Mixed, 3},
              {Full, 1}, {Mixed, 1}, {Full, 1}, {Mixed, 3}, {Empty, 207},
              {Mixed, 3}, {Empty, 1001}, {Mixed, 2}, {Empty, 33446}},
             {0x3d7f3dff, 0xffff3dff, 0x7f3dffff, 0xff7fff3d, 0xff3dffff,
              0xe7ffffff, 0x1fffffff, 0x03ffffff, 0x007fffff, 0x7f7f7f7f,
              0x7f7f7f7f, 0x007e7e7e, 0x00007f7f}};
        /** Code Point Ranges for Geor
        [1417, 1417], [4256, 4293], [4295, 4295], [4301, 4301],
        [4304, 4346], [4348, 4351], [11520, 11557], [11559, 11559],
        [11565, 11565]**/
        const UnicodeSet geor_Ext 
            {{{Empty, 44}, {Mixed, 1}, {Empty, 88}, {Full, 1}, {Mixed, 2},
              {Empty, 224}, {Full, 1}, {Mixed, 1}, {Empty, 34454}},
             {0x00000200, 0xffff20bf, 0xf7ffffff, 0x000020bf}};
        /** Code Point Ranges for Glag
        [1159, 1159], [11264, 11310], [11312, 11358], [42607, 42607]**/
        const UnicodeSet glag_Ext 
            {{{Empty, 36}, {Mixed, 1}, {Empty, 315}, {Full, 1}, {Mixed, 2},
              {Empty, 976}, {Mixed, 1}, {Empty, 33484}},
             {0x00000080, 0xffff7fff, 0x7fffffff, 0x00008000}};
        /** Code Point Ranges for Goth
        [66352, 66378]**/
        const UnicodeSet goth_Ext 
            {{{Empty, 2073}, {Mixed, 2}, {Empty, 32741}},
             {0xffff0000, 0x000007ff}};
        /** Code Point Ranges for Gran
        [2385, 2386], [2404, 2405], [2986, 2986], [2997, 2997],
        [3046, 3058], [7376, 7376], [7378, 7379], [7410, 7412],
        [7416, 7417], [8432, 8432], [70400, 70403], [70405, 70412],
        [70415, 70416], [70419, 70440], [70442, 70448], [70450, 70451],
        [70453, 70457], [70460, 70468], [70471, 70472], [70475, 70477],
        [70480, 70480], [70487, 70487], [70493, 70499], [70502, 70508],
        [70512, 70516]**/
        const UnicodeSet gran_Ext 
            {{{Empty, 74}, {Mixed, 2}, {Empty, 17}, {Mixed, 1}, {Empty, 1},
              {Mixed, 1}, {Empty, 134}, {Mixed, 2}, {Empty, 31}, {Mixed, 1},
              {Empty, 1936}, {Mixed, 4}, {Empty, 32612}},
             {0x00060000, 0x00000030, 0x00200400, 0x0007ffc0, 0x000d0000,
              0x031c0000, 0x00010000, 0xfff99fef, 0xf3edfdff, 0xe081399f,
              0x001f1fcf}};
        /** Code Point Ranges for Grek
        [834, 834], [837, 837], [880, 883], [885, 887], [890, 893],
        [895, 895], [900, 900], [902, 902], [904, 906], [908, 908],
        [910, 929], [931, 993], [1008, 1023], [7462, 7466], [7517, 7521],
        [7526, 7530], [7615, 7617], [7936, 7957], [7960, 7965],
        [7968, 8005], [8008, 8013], [8016, 8023], [8025, 8025],
        [8027, 8027], [8029, 8029], [8031, 8061], [8064, 8116],
        [8118, 8132], [8134, 8147], [8150, 8155], [8157, 8175],
        [8178, 8180], [8182, 8190], [8486, 8486], [43877, 43877],
        [65856, 65932], [65952, 65952], [119296, 119365]**/
        const UnicodeSet grek_Ext 
            {{{Empty, 26}, {Mixed, 4}, {Full, 1}, {Mixed, 1}, {Empty, 201},
              {Mixed, 3}, {Empty, 1}, {Mixed, 2}, {Empty, 9}, {Mixed, 1},
              {Full, 1}, {Mixed, 2}, {Full, 1}, {Mixed, 3}, {Empty, 9},
              {Mixed, 1}, {Empty, 1105}, {Mixed, 1}, {Empty, 686},
              {Full, 2}, {Mixed, 2}, {Empty, 1666}, {Full, 2}, {Mixed, 1},
              {Empty, 31085}},
             {0x00000024, 0xbcef0000, 0xffffd750, 0xfffffffb, 0xffff0003,
              0x000007c0, 0xe0000000, 0x000007c3, 0x80000000, 0x00000003,
              0x3f3fffff, 0xaaff3f3f, 0x3fffffff, 0xffdfffff, 0xefcfffdf,
              0x7fdcffff, 0x00000040, 0x00000020, 0x00001fff, 0x00000001,
              0x0000003f}};
        /** Code Point Ranges for Gujr
        [2385, 2386], [2404, 2405], [2689, 2691], [2693, 2701],
        [2703, 2705], [2707, 2728], [2730, 2736], [2738, 2739],
        [2741, 2745], [2748, 2757], [2759, 2761], [2763, 2765],
        [2768, 2768], [2784, 2787], [2790, 2801], [2809, 2809],
        [43056, 43065]**/
        const UnicodeSet gujr_Ext 
            {{{Empty, 74}, {Mixed, 2}, {Empty, 8}, {Mixed, 4},
              {Empty, 1257}, {Mixed, 1}, {Empty, 33470}},
             {0x00060000, 0x00000030, 0xfffbbfee, 0xf3edfdff, 0x00013bbf,
              0x0203ffcf, 0x03ff0000}};
        /** Code Point Ranges for Guru
        [2385, 2386], [2404, 2405], [2561, 2563], [2565, 2570],
        [2575, 2576], [2579, 2600], [2602, 2608], [2610, 2611],
        [2613, 2614], [2616, 2617], [2620, 2620], [2622, 2626],
        [2631, 2632], [2635, 2637], [2641, 2641], [2649, 2652],
        [2654, 2654], [2662, 2677], [43056, 43065]**/
        const UnicodeSet guru_Ext 
            {{{Empty, 74}, {Mixed, 2}, {Empty, 4}, {Mixed, 4},
              {Empty, 1261}, {Mixed, 1}, {Empty, 33470}},
             {0x00060000, 0x00000030, 0xfff987ee, 0xd36dfdff, 0x5e023987,
              0x003fffc0, 0x03ff0000}};
        /** Code Point Ranges for Hang
        [4352, 4607], [12289, 12291], [12296, 12305], [12307, 12319],
        [12334, 12336], [12343, 12343], [12350, 12351], [12539, 12539],
        [12593, 12686], [12736, 12771], [12800, 12830], [12832, 12867],
        [12896, 12926], [12928, 12976], [12992, 13003], [13144, 13168],
        [13179, 13183], [13280, 13310], [43360, 43388], [44032, 55203],
        [55216, 55238], [55243, 55291], [65093, 65094], [65377, 65381],
        [65440, 65470], [65474, 65479], [65482, 65487], [65490, 65495],
        [65498, 65500]**/
        const UnicodeSet hang_Ext 
            {{{Empty, 136}, {Full, 8}, {Empty, 240}, {Mixed, 2}, {Empty, 5},
              {Mixed, 1}, {Empty, 1}, {Mixed, 1}, {Full, 2}, {Mixed, 1},
              {Empty, 1}, {Full, 1}, {Mixed, 2}, {Full, 1}, {Mixed, 2},
              {Full, 1}, {Mixed, 2}, {Empty, 3}, {Mixed, 2}, {Empty, 3},
              {Mixed, 1}, {Empty, 939}, {Mixed, 1}, {Empty, 20},
              {Full, 349}, {Mixed, 3}, {Empty, 306}, {Mixed, 1}, {Empty, 8},
              {Mixed, 1}, {Empty, 1}, {Mixed, 2}, {Empty, 32769}},
             {0xfffbff0e, 0xc081c000, 0x08000000, 0xfffe0000, 0x00007fff,
              0x0000000f, 0x7fffffff, 0x0000000f, 0x7fffffff, 0x0001ffff,
              0x00000fff, 0xff000000, 0xf801ffff, 0x7fffffff, 0x1fffffff,
              0xffff000f, 0xfffff87f, 0x0fffffff, 0x00000060, 0x0000003e,
              0x7fffffff, 0x1cfcfcfc}};
        /** Code Point Ranges for Hani
        [11904, 11929], [11931, 12019], [12032, 12245], [12289, 12291],
        [12293, 12305], [12307, 12319], [12321, 12333], [12336, 12336],
        [12343, 12351], [12539, 12539], [12688, 12703], [12736, 12771],
        [12832, 12867], [12928, 12976], [12992, 13003], [13144, 13168],
        [13179, 13183], [13280, 13310], [13312, 19893], [19968, 40917],
        [63744, 64109], [64112, 64217], [65093, 65094], [65377, 65381],
        [119648, 119665], [131072, 173782], [173824, 177972],
        [177984, 178205], [178208, 183969], [194560, 195101]**/
        const UnicodeSet hani_Ext 
            {{{Empty, 372}, {Mixed, 1}, {Full, 2}, {Mixed, 1}, {Full, 6},
              {Mixed, 1}, {Empty, 1}, {Mixed, 2}, {Empty, 5}, {Mixed, 1},
              {Empty, 4}, {Mixed, 1}, {Empty, 1}, {Full, 1}, {Mixed, 1},
              {Empty, 1}, {Full, 1}, {Mixed, 1}, {Empty, 1}, {Full, 1},
              {Mixed, 2}, {Empty, 3}, {Mixed, 2}, {Empty, 3}, {Mixed, 1},
              {Full, 205}, {Mixed, 1}, {Empty, 2}, {Full, 654}, {Mixed, 1},
              {Empty, 713}, {Full, 11}, {Mixed, 1}, {Full, 2}, {Mixed, 1},
              {Empty, 27}, {Mixed, 1}, {Empty, 8}, {Mixed, 1},
              {Empty, 1695}, {Mixed, 1}, {Empty, 356}, {Full, 1334},
              {Mixed, 1}, {Empty, 1}, {Full, 129}, {Mixed, 1}, {Full, 6},
              {Mixed, 1}, {Full, 180}, {Mixed, 1}, {Empty, 330}, {Full, 16},
              {Mixed, 1}, {Empty, 28719}},
             {0xfbffffff, 0x000fffff, 0x003fffff, 0xfffbffee, 0xff813ffe,
              0x08000000, 0xffff0000, 0x0000000f, 0x0000000f, 0x0001ffff,
              0x00000fff, 0xff000000, 0xf801ffff, 0x7fffffff, 0x003fffff,
              0x003fffff, 0xffff3fff, 0x03ffffff, 0x00000060, 0x0000003e,
              0x0003ffff, 0x007fffff, 0x001fffff, 0x3fffffff, 0x00000003,
              0x3fffffff}};
        /** Code Point Ranges for Hano
        [5920, 5942]**/
        const UnicodeSet hano_Ext 
            {{{Empty, 185}, {Mixed, 1}, {Empty, 34630}},
             {0x007fffff}};
        /** Code Point Ranges for Hatr
        [67808, 67826], [67828, 67829], [67835, 67839]**/
        const UnicodeSet hatr_Ext 
            {{{Empty, 2119}, {Mixed, 1}, {Empty, 32696}},
             {0xf837ffff}};
        /** Code Point Ranges for Hebr
        [1425, 1479], [1488, 1514], [1520, 1524], [64285, 64310],
        [64312, 64316], [64318, 64318], [64320, 64321], [64323, 64324],
        [64326, 64335]**/
        const UnicodeSet hebr_Ext 
            {{{Empty, 44}, {Mixed, 1}, {Full, 1}, {Mixed, 2}, {Empty, 1960},
              {Mixed, 3}, {Empty, 32805}},
             {0xfffe0000, 0xffff00ff, 0x001f07ff, 0xe0000000, 0x5f7fffff,
              0x0000ffdb}};
        /** Code Point Ranges for Hira
        [12289, 12291], [12294, 12294], [12296, 12305], [12307, 12319],
        [12336, 12341], [12343, 12343], [12348, 12351], [12353, 12438],
        [12441, 12448], [12539, 12540], [12688, 12703], [12736, 12771],
        [12832, 12867], [12928, 12976], [12992, 13003], [13144, 13168],
        [13179, 13183], [13280, 13310], [65093, 65094], [65377, 65381],
        [65392, 65392], [65438, 65439], [110593, 110593], [127488, 127488]**/
        const UnicodeSet hira_Ext 
            {{{Empty, 384}, {Mixed, 3}, {Full, 1}, {Mixed, 2}, {Empty, 1},
              {Mixed, 1}, {Empty, 4}, {Mixed, 1}, {Empty, 1}, {Full, 1},
              {Mixed, 1}, {Empty, 1}, {Full, 1}, {Mixed, 1}, {Empty, 1},
              {Full, 1}, {Mixed, 2}, {Empty, 3}, {Mixed, 2}, {Empty, 3},
              {Mixed, 1}, {Empty, 1618}, {Mixed, 1}, {Empty, 8}, {Mixed, 2},
              {Empty, 1411}, {Mixed, 1}, {Empty, 527}, {Mixed, 1},
              {Empty, 30831}},
             {0xfffbff4e, 0xf0bf0000, 0xfffffffe, 0xfe7fffff, 0x00000001,
              0x18000000, 0xffff0000, 0x0000000f, 0x0000000f, 0x0001ffff,
              0x00000fff, 0xff000000, 0xf801ffff, 0x7fffffff, 0x00000060,
              0x0001003e, 0xc0000000, 0x00000002, 0x00000001}};
        /** Code Point Ranges for Hluw
        [82944, 83526]**/
        const UnicodeSet hluw_Ext 
            {{{Empty, 2592}, {Full, 18}, {Mixed, 1}, {Empty, 32205}},
             {0x0000007f}};
        /** Code Point Ranges for Hmng
        [92928, 92997], [93008, 93017], [93019, 93025], [93027, 93047],
        [93053, 93071]**/
        const UnicodeSet hmng_Ext 
            {{{Empty, 2904}, {Full, 2}, {Mixed, 3}, {Empty, 31907}},
             {0xfbff003f, 0xe0fffffb, 0x0000ffff}};
        /** Code Point Ranges for Hrkt
        **/
        const UnicodeSet hrkt_Ext 
            {{{Empty, 34816}},
             {}};
        /** Code Point Ranges for Hung
        [68736, 68786], [68800, 68850], [68858, 68863]**/
        const UnicodeSet hung_Ext 
            {{{Empty, 2148}, {Full, 1}, {Mixed, 1}, {Full, 1}, {Mixed, 1},
              {Empty, 32664}},
             {0x0007ffff, 0xfc07ffff}};
        /** Code Point Ranges for Ital
        [66304, 66339]**/
        const UnicodeSet ital_Ext 
            {{{Empty, 2072}, {Full, 1}, {Mixed, 1}, {Empty, 32742}},
             {0x0000000f}};
        /** Code Point Ranges for Java
        [43392, 43469], [43471, 43481], [43486, 43487]**/
        const UnicodeSet java_Ext 
            {{{Empty, 1356}, {Full, 2}, {Mixed, 1}, {Empty, 33457}},
             {0xc3ffbfff}};
        /** Code Point Ranges for Kali
        [43264, 43311]**/
        const UnicodeSet kali_Ext 
            {{{Empty, 1352}, {Full, 1}, {Mixed, 1}, {Empty, 33462}},
             {0x0000ffff}};
        /** Code Point Ranges for Kana
        [12289, 12291], [12294, 12294], [12296, 12305], [12307, 12319],
        [12336, 12341], [12343, 12343], [12348, 12351], [12441, 12444],
        [12448, 12543], [12688, 12703], [12736, 12771], [12784, 12799],
        [12832, 12867], [12928, 12976], [12992, 13003], [13008, 13054],
        [13056, 13168], [13179, 13183], [13280, 13310], [65093, 65094],
        [65377, 65439], [110592, 110592]**/
        const UnicodeSet kana_Ext 
            {{{Empty, 384}, {Mixed, 2}, {Empty, 2}, {Mixed, 1}, {Full, 3},
              {Empty, 4}, {Mixed, 1}, {Empty, 1}, {Full, 1}, {Mixed, 1},
              {Empty, 1}, {Full, 1}, {Mixed, 1}, {Empty, 1}, {Full, 1},
              {Mixed, 3}, {Full, 3}, {Mixed, 1}, {Empty, 3}, {Mixed, 1},
              {Empty, 1618}, {Mixed, 1}, {Empty, 8}, {Mixed, 1}, {Full, 1},
              {Empty, 1411}, {Mixed, 1}, {Empty, 31359}},
             {0xfffbff4e, 0xf0bf0000, 0x1e000000, 0xffff0000, 0xffff000f,
              0x0000000f, 0x0001ffff, 0xffff0fff, 0x7fffffff, 0xf801ffff,
              0x7fffffff, 0x00000060, 0xfffffffe, 0x00000001}};
        /** Code Point Ranges for Khar
        [68096, 68099], [68101, 68102], [68108, 68115], [68117, 68119],
        [68121, 68147], [68152, 68154], [68159, 68167], [68176, 68184]**/
        const UnicodeSet khar_Ext 
            {{{Empty, 2128}, {Mixed, 3}, {Empty, 32685}},
             {0xfeeff06f, 0x870fffff, 0x01ff00ff}};
        /** Code Point Ranges for Khmr
        [6016, 6109], [6112, 6121], [6128, 6137], [6624, 6655]**/
        const UnicodeSet khmr_Ext 
            {{{Empty, 188}, {Full, 2}, {Mixed, 2}, {Empty, 15}, {Full, 1},
              {Empty, 34608}},
             {0x3fffffff, 0x03ff03ff}};
        /** Code Point Ranges for Khoj
        [2790, 2799], [70144, 70161], [70163, 70205]**/
        const UnicodeSet khoj_Ext 
            {{{Empty, 87}, {Mixed, 1}, {Empty, 2104}, {Mixed, 2},
              {Empty, 32622}},
             {0x0000ffc0, 0xfffbffff, 0x3fffffff}};
        /** Code Point Ranges for Knda
        [2385, 2386], [2404, 2405], [3201, 3203], [3205, 3212],
        [3214, 3216], [3218, 3240], [3242, 3251], [3253, 3257],
        [3260, 3268], [3270, 3272], [3274, 3277], [3285, 3286],
        [3294, 3294], [3296, 3299], [3302, 3311], [3313, 3314],
        [7386, 7386], [7413, 7413]**/
        const UnicodeSet knda_Ext 
            {{{Empty, 74}, {Mixed, 2}, {Empty, 24}, {Mixed, 4},
              {Empty, 126}, {Mixed, 2}, {Empty, 34584}},
             {0x00060000, 0x00000030, 0xfffddfee, 0xf3effdff, 0x40603ddf,
              0x0006ffcf, 0x04000000, 0x00200000}};
        /** Code Point Ranges for Kthi
        [2406, 2415], [43056, 43065], [69760, 69825]**/
        const UnicodeSet kthi_Ext 
            {{{Empty, 75}, {Mixed, 1}, {Empty, 1269}, {Mixed, 1},
              {Empty, 834}, {Full, 2}, {Mixed, 1}, {Empty, 32633}},
             {0x0000ffc0, 0x03ff0000, 0x00000003}};
        /** Code Point Ranges for Lana
        [6688, 6750], [6752, 6780], [6783, 6793], [6800, 6809],
        [6816, 6829]**/
        const UnicodeSet lana_Ext 
            {{{Empty, 209}, {Full, 1}, {Mixed, 4}, {Empty, 34602}},
             {0x7fffffff, 0x9fffffff, 0x03ff03ff, 0x00003fff}};
        /** Code Point Ranges for Laoo
        [3713, 3714], [3716, 3716], [3719, 3720], [3722, 3722],
        [3725, 3725], [3732, 3735], [3737, 3743], [3745, 3747],
        [3749, 3749], [3751, 3751], [3754, 3755], [3757, 3769],
        [3771, 3773], [3776, 3780], [3782, 3782], [3784, 3789],
        [3792, 3801], [3804, 3807]**/
        const UnicodeSet laoo_Ext 
            {{{Empty, 116}, {Mixed, 3}, {Empty, 34697}},
             {0xfef02596, 0x3bffecae, 0xf3ff3f5f}};
        /** Code Point Ranges for Latn
        [65, 90], [97, 122], [170, 170], [186, 186], [192, 214], [216, 246],
        [248, 696], [736, 740], [867, 879], [1157, 1158], [2385, 2386],
        [7424, 7461], [7468, 7516], [7522, 7525], [7531, 7543],
        [7545, 7614], [7680, 7935], [8305, 8305], [8319, 8319],
        [8336, 8348], [8432, 8432], [8490, 8491], [8498, 8498],
        [8526, 8526], [8544, 8584], [11360, 11391], [42786, 42887],
        [42891, 42925], [42928, 42935], [42999, 43007], [43310, 43310],
        [43824, 43866], [43868, 43876], [64256, 64262], [65313, 65338],
        [65345, 65370]**/
        const UnicodeSet latn_Ext 
            {{{Empty, 2}, {Mixed, 2}, {Empty, 1}, {Mixed, 3}, {Full, 13},
              {Mixed, 1}, {Empty, 1}, {Mixed, 1}, {Empty, 3}, {Mixed, 1},
              {Empty, 8}, {Mixed, 1}, {Empty, 37}, {Mixed, 1}, {Empty, 157},
              {Full, 1}, {Mixed, 3}, {Full, 1}, {Mixed, 1}, {Empty, 2},
              {Full, 8}, {Empty, 11}, {Mixed, 2}, {Empty, 2}, {Mixed, 1},
              {Empty, 1}, {Mixed, 2}, {Full, 1}, {Mixed, 1}, {Empty, 86},
              {Full, 1}, {Empty, 981}, {Mixed, 1}, {Full, 2}, {Mixed, 2},
              {Empty, 1}, {Mixed, 1}, {Empty, 9}, {Mixed, 1}, {Empty, 15},
              {Mixed, 3}, {Empty, 636}, {Mixed, 1}, {Empty, 32}, {Mixed, 2},
              {Empty, 32773}},
             {0x07fffffe, 0x07fffffe, 0x04000400, 0xff7fffff, 0xff7fffff,
              0x01ffffff, 0x0000001f, 0x0000fff8, 0x00000060, 0x00060000,
              0xfffff03f, 0x1fffffff, 0xfefff83c, 0x7fffffff, 0x80020000,
              0x1fff0000, 0x00010000, 0x00040c00, 0x00004000, 0x000001ff,
              0xfffffffc, 0xfffff8ff, 0x00ff3fff, 0xff800000, 0x00004000,
              0xffff0000, 0xf7ffffff, 0x0000001f, 0x0000007f, 0x07fffffe,
              0x07fffffe}};
        /** Code Point Ranges for Lepc
        [7168, 7223], [7227, 7241], [7245, 7247]**/
        const UnicodeSet lepc_Ext 
            {{{Empty, 224}, {Full, 1}, {Mixed, 2}, {Empty, 34589}},
             {0xf8ffffff, 0x0000e3ff}};
        /** Code Point Ranges for Limb
        [2405, 2405], [6400, 6430], [6432, 6443], [6448, 6459],
        [6464, 6464], [6468, 6479]**/
        const UnicodeSet limb_Ext 
            {{{Empty, 75}, {Mixed, 1}, {Empty, 124}, {Mixed, 3},
              {Empty, 34613}},
             {0x00000020, 0x7fffffff, 0x0fff0fff, 0x0000fff1}};
        /** Code Point Ranges for Lina
        [67072, 67382], [67392, 67413], [67424, 67431]**/
        const UnicodeSet lina_Ext 
            {{{Empty, 2096}, {Full, 9}, {Mixed, 3}, {Empty, 32708}},
             {0x007fffff, 0x003fffff, 0x000000ff}};
        /** Code Point Ranges for Linb
        [65536, 65547], [65549, 65574], [65576, 65594], [65596, 65597],
        [65599, 65613], [65616, 65629], [65664, 65786], [65792, 65794],
        [65799, 65843], [65847, 65855]**/
        const UnicodeSet linb_Ext 
            {{{Empty, 2048}, {Mixed, 3}, {Empty, 1}, {Full, 3}, {Mixed, 3},
              {Empty, 32758}},
             {0xffffefff, 0xb7ffff7f, 0x3fff3fff, 0x07ffffff, 0xffffff87,
              0xff8fffff}};
        /** Code Point Ranges for Lisu
        [42192, 42239]**/
        const UnicodeSet lisu_Ext 
            {{{Empty, 1318}, {Mixed, 1}, {Full, 1}, {Empty, 33496}},
             {0xffff0000}};
        /** Code Point Ranges for Lyci
        [66176, 66204]**/
        const UnicodeSet lyci_Ext 
            {{{Empty, 2068}, {Mixed, 1}, {Empty, 32747}},
             {0x1fffffff}};
        /** Code Point Ranges for Lydi
        [67872, 67897], [67903, 67903]**/
        const UnicodeSet lydi_Ext 
            {{{Empty, 2121}, {Mixed, 1}, {Empty, 32694}},
             {0x83ffffff}};
        /** Code Point Ranges for Mahj
        [2404, 2415], [43056, 43065], [69968, 70006]**/
        const UnicodeSet mahj_Ext 
            {{{Empty, 75}, {Mixed, 1}, {Empty, 1269}, {Mixed, 1},
              {Empty, 840}, {Mixed, 2}, {Empty, 32628}},
             {0x0000fff0, 0x03ff0000, 0xffff0000, 0x007fffff}};
        /** Code Point Ranges for Mand
        [1600, 1600], [2112, 2139], [2142, 2142]**/
        const UnicodeSet mand_Ext 
            {{{Empty, 50}, {Mixed, 1}, {Empty, 15}, {Mixed, 1},
              {Empty, 34749}},
             {0x00000001, 0x4fffffff}};
        /** Code Point Ranges for Mani
        [1600, 1600], [68288, 68326], [68331, 68342]**/
        const UnicodeSet mani_Ext 
            {{{Empty, 50}, {Mixed, 1}, {Empty, 2083}, {Full, 1}, {Mixed, 1},
              {Empty, 32680}},
             {0x00000001, 0x007ff87f}};
        /** Code Point Ranges for Mend
        [124928, 125124], [125127, 125142]**/
        const UnicodeSet mend_Ext 
            {{{Empty, 3904}, {Full, 6}, {Mixed, 1}, {Empty, 30905}},
             {0x007fff9f}};
        /** Code Point Ranges for Merc
        [68000, 68023], [68028, 68047], [68050, 68095]**/
        const UnicodeSet merc_Ext 
            {{{Empty, 2125}, {Mixed, 2}, {Full, 1}, {Empty, 32688}},
             {0xf0ffffff, 0xfffcffff}};
        /** Code Point Ranges for Mero
        [67968, 67999]**/
        const UnicodeSet mero_Ext 
            {{{Empty, 2124}, {Full, 1}, {Empty, 32691}},
             {}};
        /** Code Point Ranges for Mlym
        [2385, 2386], [2404, 2405], [3329, 3331], [3333, 3340],
        [3342, 3344], [3346, 3386], [3389, 3396], [3398, 3400],
        [3402, 3406], [3415, 3415], [3423, 3427], [3430, 3445],
        [3449, 3455], [7386, 7386]**/
        const UnicodeSet mlym_Ext 
            {{{Empty, 74}, {Mixed, 2}, {Empty, 28}, {Mixed, 4},
              {Empty, 122}, {Mixed, 1}, {Empty, 34585}},
             {0x00060000, 0x00000030, 0xfffddfee, 0xe7ffffff, 0x80807ddf,
              0xfe3fffcf, 0x04000000}};
        /** Code Point Ranges for Modi
        [43056, 43065], [71168, 71236], [71248, 71257]**/
        const UnicodeSet modi_Ext 
            {{{Empty, 1345}, {Mixed, 1}, {Empty, 878}, {Full, 2},
              {Mixed, 1}, {Empty, 32589}},
             {0x03ff0000, 0x03ff001f}};
        /** Code Point Ranges for Mong
        [6144, 6158], [6160, 6169], [6176, 6263], [6272, 6314]**/
        const UnicodeSet mong_Ext 
            {{{Empty, 192}, {Mixed, 1}, {Full, 2}, {Mixed, 1}, {Full, 1},
              {Mixed, 1}, {Empty, 34618}},
             {0x03ff7fff, 0x00ffffff, 0x000007ff}};
        /** Code Point Ranges for Mroo
        [92736, 92766], [92768, 92777], [92782, 92783]**/
        const UnicodeSet mroo_Ext 
            {{{Empty, 2898}, {Mixed, 2}, {Empty, 31916}},
             {0x7fffffff, 0x0000c3ff}};
        /** Code Point Ranges for Mtei
        [43744, 43766], [43968, 44013], [44016, 44025]**/
        const UnicodeSet mtei_Ext 
            {{{Empty, 1367}, {Mixed, 1}, {Empty, 6}, {Full, 1}, {Mixed, 1},
              {Empty, 33440}},
             {0x007fffff, 0x03ff3fff}};
        /** Code Point Ranges for Mult
        [2662, 2671], [70272, 70278], [70280, 70280], [70282, 70285],
        [70287, 70301], [70303, 70313]**/
        const UnicodeSet mult_Ext 
            {{{Empty, 83}, {Mixed, 1}, {Empty, 2112}, {Mixed, 2},
              {Empty, 32618}},
             {0x0000ffc0, 0xbfffbd7f, 0x000003ff}};
        /** Code Point Ranges for Mymr
        [4096, 4255], [43310, 43310], [43488, 43518], [43616, 43647]**/
        const UnicodeSet mymr_Ext 
            {{{Empty, 128}, {Full, 5}, {Empty, 1220}, {Mixed, 1},
              {Empty, 5}, {Mixed, 1}, {Empty, 3}, {Full, 1}, {Empty, 33452}},
             {0x00004000, 0x7fffffff}};
        /** Code Point Ranges for Narb
        [68224, 68255]**/
        const UnicodeSet narb_Ext 
            {{{Empty, 2132}, {Full, 1}, {Empty, 32683}},
             {}};
        /** Code Point Ranges for Nbat
        [67712, 67742], [67751, 67759]**/
        const UnicodeSet nbat_Ext 
            {{{Empty, 2116}, {Mixed, 2}, {Empty, 32698}},
             {0x7fffffff, 0x0000ff80}};
        /** Code Point Ranges for Nkoo
        [1984, 2042]**/
        const UnicodeSet nkoo_Ext 
            {{{Empty, 62}, {Full, 1}, {Mixed, 1}, {Empty, 34752}},
             {0x07ffffff}};
        /** Code Point Ranges for Ogam
        [5760, 5788]**/
        const UnicodeSet ogam_Ext 
            {{{Empty, 180}, {Mixed, 1}, {Empty, 34635}},
             {0x1fffffff}};
        /** Code Point Ranges for Olck
        [7248, 7295]**/
        const UnicodeSet olck_Ext 
            {{{Empty, 226}, {Mixed, 1}, {Full, 1}, {Empty, 34588}},
             {0xffff0000}};
        /** Code Point Ranges for Orkh
        [68608, 68680]**/
        const UnicodeSet orkh_Ext 
            {{{Empty, 2144}, {Full, 2}, {Mixed, 1}, {Empty, 32669}},
             {0x000001ff}};
        /** Code Point Ranges for Orya
        [2385, 2386], [2404, 2405], [2817, 2819], [2821, 2828],
        [2831, 2832], [2835, 2856], [2858, 2864], [2866, 2867],
        [2869, 2873], [2876, 2884], [2887, 2888], [2891, 2893],
        [2902, 2903], [2908, 2909], [2911, 2915], [2918, 2935]**/
        const UnicodeSet orya_Ext 
            {{{Empty, 74}, {Mixed, 2}, {Empty, 12}, {Mixed, 4},
              {Empty, 34724}},
             {0x00060000, 0x00000030, 0xfff99fee, 0xf3edfdff, 0xb0c0399f,
              0x00ffffcf}};
        /** Code Point Ranges for Osma
        [66688, 66717], [66720, 66729]**/
        const UnicodeSet osma_Ext 
            {{{Empty, 2084}, {Mixed, 2}, {Empty, 32730}},
             {0x3fffffff, 0x000003ff}};
        /** Code Point Ranges for Palm
        [67680, 67711]**/
        const UnicodeSet palm_Ext 
            {{{Empty, 2115}, {Full, 1}, {Empty, 32700}},
             {}};
        /** Code Point Ranges for Pauc
        [72384, 72440]**/
        const UnicodeSet pauc_Ext 
            {{{Empty, 2262}, {Full, 1}, {Mixed, 1}, {Empty, 32552}},
             {0x01ffffff}};
        /** Code Point Ranges for Perm
        [1155, 1155], [66384, 66426]**/
        const UnicodeSet perm_Ext 
            {{{Empty, 36}, {Mixed, 1}, {Empty, 2037}, {Mixed, 2},
              {Empty, 32740}},
             {0x00000008, 0xffff0000, 0x07ffffff}};
        /** Code Point Ranges for Phag
        [6146, 6147], [6149, 6149], [43072, 43127]**/
        const UnicodeSet phag_Ext 
            {{{Empty, 192}, {Mixed, 1}, {Empty, 1153}, {Full, 1},
              {Mixed, 1}, {Empty, 33468}},
             {0x0000002c, 0x00ffffff}};
        /** Code Point Ranges for Phli
        [68448, 68466], [68472, 68479]**/
        const UnicodeSet phli_Ext 
            {{{Empty, 2139}, {Mixed, 1}, {Empty, 32676}},
             {0xff07ffff}};
        /** Code Point Ranges for Phlp
        [1600, 1600], [68480, 68497], [68505, 68508], [68521, 68527]**/
        const UnicodeSet phlp_Ext 
            {{{Empty, 50}, {Mixed, 1}, {Empty, 2089}, {Mixed, 2},
              {Empty, 32674}},
             {0x00000001, 0x1e03ffff, 0x0000fe00}};
        /** Code Point Ranges for Phnx
        [67840, 67867], [67871, 67871]**/
        const UnicodeSet phnx_Ext 
            {{{Empty, 2120}, {Mixed, 1}, {Empty, 32695}},
             {0x8fffffff}};
        /** Code Point Ranges for Plrd
        [93952, 94020], [94032, 94078], [94095, 94111]**/
        const UnicodeSet plrd_Ext 
            {{{Empty, 2936}, {Full, 2}, {Mixed, 3}, {Empty, 31875}},
             {0xffff001f, 0x7fffffff, 0xffff8000}};
        /** Code Point Ranges for Prti
        [68416, 68437], [68440, 68447]**/
        const UnicodeSet prti_Ext 
            {{{Empty, 2138}, {Mixed, 1}, {Empty, 32677}},
             {0xff3fffff}};
        /** Code Point Ranges for Rjng
        [43312, 43347], [43359, 43359]**/
        const UnicodeSet rjng_Ext 
            {{{Empty, 1353}, {Mixed, 2}, {Empty, 33461}},
             {0xffff0000, 0x800fffff}};
        /** Code Point Ranges for Runr
        [5792, 5866], [5870, 5880]**/
        const UnicodeSet runr_Ext 
            {{{Empty, 181}, {Full, 2}, {Mixed, 1}, {Empty, 34632}},
             {0x01ffc7ff}};
        /** Code Point Ranges for Samr
        [2048, 2093], [2096, 2110]**/
        const UnicodeSet samr_Ext 
            {{{Empty, 64}, {Full, 1}, {Mixed, 1}, {Empty, 34750}},
             {0x7fff3fff}};
        /** Code Point Ranges for Sarb
        [68192, 68223]**/
        const UnicodeSet sarb_Ext 
            {{{Empty, 2131}, {Full, 1}, {Empty, 32684}},
             {}};
        /** Code Point Ranges for Saur
        [43136, 43204], [43214, 43225]**/
        const UnicodeSet saur_Ext 
            {{{Empty, 1348}, {Full, 2}, {Mixed, 1}, {Empty, 33465}},
             {0x03ffc01f}};
        /** Code Point Ranges for Sgnw
        [120832, 121483], [121499, 121503], [121505, 121519]**/
        const UnicodeSet sgnw_Ext 
            {{{Empty, 3776}, {Full, 20}, {Mixed, 2}, {Empty, 31018}},
             {0xf8000fff, 0x0000fffe}};
        /** Code Point Ranges for Shaw
        [66640, 66687]**/
        const UnicodeSet shaw_Ext 
            {{{Empty, 2082}, {Mixed, 1}, {Full, 1}, {Empty, 32732}},
             {0xffff0000}};
        /** Code Point Ranges for Shrd
        [2385, 2385], [7383, 7383], [7385, 7385], [7388, 7389],
        [7392, 7392], [70016, 70093], [70096, 70111]**/
        const UnicodeSet shrd_Ext 
            {{{Empty, 74}, {Mixed, 1}, {Empty, 155}, {Mixed, 2},
              {Empty, 1956}, {Full, 2}, {Mixed, 1}, {Empty, 32625}},
             {0x00020000, 0x32800000, 0x00000001, 0xffff3fff}};
        /** Code Point Ranges for Sidd
        [71040, 71093], [71096, 71133]**/
        const UnicodeSet sidd_Ext 
            {{{Empty, 2220}, {Full, 1}, {Mixed, 2}, {Empty, 32593}},
             {0xff3fffff, 0x3fffffff}};
        /** Code Point Ranges for Sind
        [2404, 2405], [43056, 43065], [70320, 70378], [70384, 70393]**/
        const UnicodeSet sind_Ext 
            {{{Empty, 75}, {Mixed, 1}, {Empty, 1269}, {Mixed, 1},
              {Empty, 851}, {Mixed, 1}, {Full, 1}, {Mixed, 1},
              {Empty, 32616}},
             {0x00000030, 0x03ff0000, 0xffff0000, 0x03ff07ff}};
        /** Code Point Ranges for Sinh
        [2404, 2405], [3458, 3459], [3461, 3478], [3482, 3505],
        [3507, 3515], [3517, 3517], [3520, 3526], [3530, 3530],
        [3535, 3540], [3542, 3542], [3544, 3551], [3558, 3567],
        [3570, 3572], [70113, 70132]**/
        const UnicodeSet sinh_Ext 
            {{{Empty, 75}, {Mixed, 1}, {Empty, 32}, {Mixed, 4},
              {Empty, 2079}, {Mixed, 1}, {Empty, 32624}},
             {0x00000030, 0xfc7fffec, 0x2ffbffff, 0xff5f847f, 0x001cffc0,
              0x001ffffe}};
        /** Code Point Ranges for Sora
        [69840, 69864], [69872, 69881]**/
        const UnicodeSet sora_Ext 
            {{{Empty, 2182}, {Mixed, 2}, {Empty, 32632}},
             {0xffff0000, 0x03ff01ff}};
        /** Code Point Ranges for Sund
        [7040, 7103], [7360, 7367]**/
        const UnicodeSet sund_Ext 
            {{{Empty, 220}, {Full, 2}, {Empty, 8}, {Mixed, 1},
              {Empty, 34585}},
             {0x000000ff}};
        /** Code Point Ranges for Sylo
        [2404, 2405], [2534, 2543], [43008, 43051]**/
        const UnicodeSet sylo_Ext 
            {{{Empty, 75}, {Mixed, 1}, {Empty, 3}, {Mixed, 1},
              {Empty, 1264}, {Full, 1}, {Mixed, 1}, {Empty, 33470}},
             {0x00000030, 0x0000ffc0, 0x00000fff}};
        /** Code Point Ranges for Syrc
        [1548, 1548], [1563, 1563], [1567, 1567], [1600, 1600],
        [1611, 1621], [1648, 1648], [1792, 1805], [1807, 1866],
        [1869, 1871]**/
        const UnicodeSet syrc_Ext 
            {{{Empty, 48}, {Mixed, 1}, {Empty, 1}, {Mixed, 2}, {Empty, 4},
              {Mixed, 1}, {Full, 1}, {Mixed, 1}, {Empty, 34757}},
             {0x88001000, 0x003ff801, 0x00010000, 0xffffbfff, 0x0000e7ff}};
        /** Code Point Ranges for Tagb
        [5941, 5942], [5984, 5996], [5998, 6000], [6002, 6003]**/
        const UnicodeSet tagb_Ext 
            {{{Empty, 185}, {Mixed, 1}, {Empty, 1}, {Mixed, 1},
              {Empty, 34628}},
             {0x00600000, 0x000ddfff}};
        /** Code Point Ranges for Takr
        [2404, 2405], [43056, 43065], [71296, 71351], [71360, 71369]**/
        const UnicodeSet takr_Ext 
            {{{Empty, 75}, {Mixed, 1}, {Empty, 1269}, {Mixed, 1},
              {Empty, 882}, {Full, 1}, {Mixed, 2}, {Empty, 32585}},
             {0x00000030, 0x03ff0000, 0x00ffffff, 0x000003ff}};
        /** Code Point Ranges for Tale
        [4160, 4169], [6480, 6509], [6512, 6516]**/
        const UnicodeSet tale_Ext 
            {{{Empty, 130}, {Mixed, 1}, {Empty, 71}, {Mixed, 2},
              {Empty, 34612}},
             {0x000003ff, 0xffff0000, 0x001f3fff}};
        /** Code Point Ranges for Talu
        [6528, 6571], [6576, 6601], [6608, 6618], [6622, 6623]**/
        const UnicodeSet talu_Ext 
            {{{Empty, 204}, {Full, 1}, {Mixed, 2}, {Empty, 34609}},
             {0xffff0fff, 0xc7ff03ff}};
        /** Code Point Ranges for Taml
        [2385, 2386], [2404, 2405], [2946, 2947], [2949, 2954],
        [2958, 2960], [2962, 2965], [2969, 2970], [2972, 2972],
        [2974, 2975], [2979, 2980], [2984, 2986], [2990, 3001],
        [3006, 3010], [3014, 3016], [3018, 3021], [3024, 3024],
        [3031, 3031], [3046, 3066], [7386, 7386], [43251, 43251]**/
        const UnicodeSet taml_Ext 
            {{{Empty, 74}, {Mixed, 2}, {Empty, 16}, {Mixed, 4},
              {Empty, 134}, {Mixed, 1}, {Empty, 1120}, {Mixed, 1},
              {Empty, 33464}},
             {0x00060000, 0x00000030, 0xd63dc7ec, 0xc3ffc718, 0x00813dc7,
              0x07ffffc0, 0x04000000, 0x00080000}};
        /** Code Point Ranges for Tavt
        [43648, 43714], [43739, 43743]**/
        const UnicodeSet tavt_Ext 
            {{{Empty, 1364}, {Full, 2}, {Mixed, 1}, {Empty, 33449}},
             {0xf8000007}};
        /** Code Point Ranges for Telu
        [2385, 2386], [2404, 2405], [3072, 3075], [3077, 3084],
        [3086, 3088], [3090, 3112], [3114, 3129], [3133, 3140],
        [3142, 3144], [3146, 3149], [3157, 3158], [3160, 3162],
        [3168, 3171], [3174, 3183], [3192, 3199], [7386, 7386]**/
        const UnicodeSet telu_Ext 
            {{{Empty, 74}, {Mixed, 2}, {Empty, 20}, {Mixed, 4},
              {Empty, 130}, {Mixed, 1}, {Empty, 34585}},
             {0x00060000, 0x00000030, 0xfffddfef, 0xe3fffdff, 0x07603ddf,
              0xff00ffcf, 0x04000000}};
        /** Code Point Ranges for Tfng
        [11568, 11623], [11631, 11632], [11647, 11647]**/
        const UnicodeSet tfng_Ext 
            {{{Empty, 361}, {Mixed, 1}, {Full, 1}, {Mixed, 1},
              {Empty, 34452}},
             {0xffff0000, 0x800180ff}};
        /** Code Point Ranges for Tglg
        [5888, 5900], [5902, 5908], [5941, 5942]**/
        const UnicodeSet tglg_Ext 
            {{{Empty, 184}, {Mixed, 2}, {Empty, 34630}},
             {0x001fdfff, 0x00600000}};
        /** Code Point Ranges for Thaa
        [1548, 1548], [1563, 1563], [1567, 1567], [1632, 1641],
        [1920, 1969], [65010, 65010], [65021, 65021]**/
        const UnicodeSet thaa_Ext 
            {{{Empty, 48}, {Mixed, 1}, {Empty, 2}, {Mixed, 1}, {Empty, 8},
              {Full, 1}, {Mixed, 1}, {Empty, 1969}, {Mixed, 1},
              {Empty, 32784}},
             {0x88001000, 0x000003ff, 0x0003ffff, 0x20040000}};
        /** Code Point Ranges for Thai
        [3585, 3642], [3648, 3675]**/
        const UnicodeSet thai_Ext 
            {{{Empty, 112}, {Mixed, 3}, {Empty, 34701}},
             {0xfffffffe, 0x07ffffff, 0x0fffffff}};
        /** Code Point Ranges for Tibt
        [3840, 3911], [3913, 3948], [3953, 3991], [3993, 4028],
        [4030, 4044], [4046, 4052], [4057, 4058]**/
        const UnicodeSet tibt_Ext 
            {{{Empty, 120}, {Full, 2}, {Mixed, 5}, {Empty, 34689}},
             {0xfffffeff, 0xfffe1fff, 0xfeffffff, 0xdfffffff, 0x061fdfff}};
        /** Code Point Ranges for Tirh
        [2404, 2405], [43056, 43065], [70784, 70855], [70864, 70873]**/
        const UnicodeSet tirh_Ext 
            {{{Empty, 75}, {Mixed, 1}, {Empty, 1269}, {Mixed, 1},
              {Empty, 866}, {Full, 2}, {Mixed, 1}, {Empty, 32601}},
             {0x00000030, 0x03ff0000, 0x03ff00ff}};
        /** Code Point Ranges for Ugar
        [66432, 66461], [66463, 66463]**/
        const UnicodeSet ugar_Ext 
            {{{Empty, 2076}, {Mixed, 1}, {Empty, 32739}},
             {0xbfffffff}};
        /** Code Point Ranges for Vaii
        [42240, 42539]**/
        const UnicodeSet vaii_Ext 
            {{{Empty, 1320}, {Full, 9}, {Mixed, 1}, {Empty, 33486}},
             {0x00000fff}};
        /** Code Point Ranges for Wara
        [71840, 71922], [71935, 71935]**/
        const UnicodeSet wara_Ext 
            {{{Empty, 2245}, {Full, 2}, {Mixed, 1}, {Empty, 32568}},
             {0x8007ffff}};
        /** Code Point Ranges for Xpeo
        [66464, 66499], [66504, 66517]**/
        const UnicodeSet xpeo_Ext 
            {{{Empty, 2077}, {Full, 1}, {Mixed, 1}, {Empty, 32737}},
             {0x003fff0f}};
        /** Code Point Ranges for Xsux
        [73728, 74649], [74752, 74862], [74864, 74868], [74880, 75075]**/
        const UnicodeSet xsux_Ext 
            {{{Empty, 2304}, {Full, 28}, {Mixed, 1}, {Empty, 3}, {Full, 3},
              {Mixed, 1}, {Full, 6}, {Mixed, 1}, {Empty, 32469}},
             {0x03ffffff, 0x001f7fff, 0x0000000f}};
        /** Code Point Ranges for Yiii
        [12289, 12290], [12296, 12305], [12308, 12315], [12539, 12539],
        [40960, 42124], [42128, 42182], [65377, 65381]**/
        const UnicodeSet yiii_Ext 
            {{{Empty, 384}, {Mixed, 1}, {Empty, 6}, {Mixed, 1},
              {Empty, 888}, {Full, 36}, {Mixed, 1}, {Full, 1}, {Mixed, 1},
              {Empty, 724}, {Mixed, 1}, {Empty, 32772}},
             {0x0ff3ff06, 0x08000000, 0xffff1fff, 0x0000007f, 0x0000003e}};
        /** Code Point Ranges for Zinh
        [768, 879], [1157, 1158], [1611, 1621], [1648, 1648], [2385, 2386],
        [6832, 6846], [7376, 7378], [7380, 7392], [7394, 7400],
        [7405, 7405], [7412, 7412], [7416, 7417], [7616, 7669],
        [7676, 7679], [8204, 8205], [8400, 8432], [12330, 12333],
        [12441, 12442], [65024, 65039], [65056, 65069], [66045, 66045],
        [66272, 66272], [119143, 119145], [119163, 119170],
        [119173, 119179], [119210, 119213], [917760, 917999]**/
        const UnicodeSet zinh_Ext 
            {{{Empty, 24}, {Full, 3}, {Mixed, 1}, {Empty, 8}, {Mixed, 1},
              {Empty, 13}, {Mixed, 2}, {Empty, 22}, {Mixed, 1},
              {Empty, 138}, {Mixed, 1}, {Empty, 16}, {Mixed, 2}, {Empty, 6},
              {Full, 1}, {Mixed, 1}, {Empty, 16}, {Mixed, 1}, {Empty, 5},
              {Mixed, 2}, {Empty, 121}, {Mixed, 1}, {Empty, 2}, {Mixed, 1},
              {Empty, 1643}, {Mixed, 2}, {Empty, 29}, {Mixed, 1},
              {Empty, 7}, {Mixed, 1}, {Empty, 1651}, {Mixed, 3},
              {Empty, 24954}, {Full, 7}, {Mixed, 1}, {Empty, 6128}},
             {0x0000ffff, 0x00000060, 0x003ff800, 0x00010000, 0x00060000,
              0x7fff0000, 0xfff70000, 0x031021fd, 0xf03fffff, 0x00003000,
              0xffff0000, 0x0001ffff, 0x00003c00, 0x06000000, 0x0000ffff,
              0x00003fff, 0x20000000, 0x00000001, 0xf8000380, 0x00000fe7,
              0x00003c00, 0x0000ffff}};
        /** Code Point Ranges for Zyyy
        [0, 64], [91, 96], [123, 169], [171, 185], [187, 191], [215, 215],
        [247, 247], [697, 735], [741, 745], [748, 767], [884, 884],
        [894, 894], [901, 901], [903, 903], [1417, 1417], [1541, 1541],
        [1548, 1548], [1563, 1564], [1567, 1567], [1600, 1600],
        [1757, 1757], [2404, 2405], [3647, 3647], [4053, 4056],
        [4347, 4347], [5867, 5869], [5941, 5942], [6146, 6147],
        [6149, 6149], [7379, 7379], [7393, 7393], [7401, 7404],
        [7406, 7411], [7413, 7414], [8192, 8203], [8206, 8292],
        [8294, 8304], [8308, 8318], [8320, 8334], [8352, 8382],
        [8448, 8485], [8487, 8489], [8492, 8497], [8499, 8525],
        [8527, 8543], [8585, 8587], [8592, 9210], [9216, 9254],
        [9280, 9290], [9312, 10239], [10496, 11123], [11126, 11157],
        [11160, 11193], [11197, 11208], [11210, 11217], [11244, 11247],
        [11776, 11842], [12272, 12283], [12288, 12292], [12294, 12294],
        [12296, 12320], [12336, 12343], [12348, 12351], [12443, 12444],
        [12448, 12448], [12539, 12540], [12688, 12703], [12736, 12771],
        [12832, 12895], [12927, 13007], [13144, 13311], [19904, 19967],
        [42752, 42785], [42888, 42890], [43056, 43065], [43310, 43310],
        [43471, 43471], [43867, 43867], [64830, 64831], [65040, 65049],
        [65072, 65106], [65108, 65126], [65128, 65131], [65279, 65279],
        [65281, 65312], [65339, 65344], [65371, 65381], [65392, 65392],
        [65438, 65439], [65504, 65510], [65512, 65518], [65529, 65533],
        [65792, 65794], [65799, 65843], [65847, 65855], [65936, 65947],
        [66000, 66044], [66273, 66299], [113824, 113827], [118784, 119029],
        [119040, 119078], [119081, 119142], [119146, 119162],
        [119171, 119172], [119180, 119209], [119214, 119272],
        [119552, 119638], [119648, 119665], [119808, 119892],
        [119894, 119964], [119966, 119967], [119970, 119970],
        [119973, 119974], [119977, 119980], [119982, 119993],
        [119995, 119995], [119997, 120003], [120005, 120069],
        [120071, 120074], [120077, 120084], [120086, 120092],
        [120094, 120121], [120123, 120126], [120128, 120132],
        [120134, 120134], [120138, 120144], [120146, 120485],
        [120488, 120779], [120782, 120831], [126976, 127019],
        [127024, 127123], [127136, 127150], [127153, 127167],
        [127169, 127183], [127185, 127221], [127232, 127244],
        [127248, 127278], [127280, 127339], [127344, 127386],
        [127462, 127487], [127489, 127490], [127504, 127546],
        [127552, 127560], [127568, 127569], [127744, 128377],
        [128379, 128419], [128421, 128720], [128736, 128748],
        [128752, 128755], [128768, 128883], [128896, 128980],
        [129024, 129035], [129040, 129095], [129104, 129113],
        [129120, 129159], [129168, 129197], [129296, 129304],
        [129408, 129412], [129472, 129472], [917505, 917505],
        [917536, 917631]**/
        const UnicodeSet zyyy_Ext 
            {{{Full, 2}, {Mixed, 2}, {Full, 1}, {Mixed, 3}, {Empty, 13},
              {Mixed, 1}, {Full, 1}, {Mixed, 1}, {Empty, 3}, {Mixed, 2},
              {Empty, 15}, {Mixed, 1}, {Empty, 3}, {Mixed, 1}, {Empty, 1},
              {Mixed, 1}, {Empty, 3}, {Mixed, 1}, {Empty, 20}, {Mixed, 1},
              {Empty, 37}, {Mixed, 1}, {Empty, 12}, {Mixed, 1}, {Empty, 8},
              {Mixed, 1}, {Empty, 47}, {Mixed, 1}, {Empty, 1}, {Mixed, 1},
              {Empty, 6}, {Mixed, 1}, {Empty, 37}, {Mixed, 2}, {Empty, 24},
              {Mixed, 1}, {Full, 2}, {Mixed, 3}, {Empty, 2}, {Full, 1},
              {Mixed, 2}, {Empty, 1}, {Mixed, 1}, {Full, 18}, {Mixed, 1},
              {Full, 1}, {Mixed, 2}, {Full, 29}, {Empty, 8}, {Full, 19},
              {Mixed, 5}, {Empty, 16}, {Full, 2}, {Mixed, 1}, {Empty, 12},
              {Mixed, 3}, {Empty, 2}, {Mixed, 2}, {Empty, 1}, {Mixed, 1},
              {Empty, 4}, {Mixed, 1}, {Empty, 1}, {Full, 1}, {Mixed, 1},
              {Empty, 1}, {Full, 2}, {Mixed, 1}, {Full, 2}, {Mixed, 1},
              {Empty, 3}, {Mixed, 1}, {Full, 5}, {Empty, 206}, {Full, 2},
              {Empty, 712}, {Full, 1}, {Mixed, 1}, {Empty, 2}, {Mixed, 1},
              {Empty, 4}, {Mixed, 1}, {Empty, 7}, {Mixed, 1}, {Empty, 4},
              {Mixed, 1}, {Empty, 11}, {Mixed, 1}, {Empty, 654}, {Mixed, 1},
              {Empty, 6}, {Mixed, 4}, {Empty, 3}, {Mixed, 6}, {Empty, 2},
              {Mixed, 1}, {Empty, 8}, {Mixed, 2}, {Empty, 2}, {Mixed, 1},
              {Empty, 1}, {Mixed, 2}, {Empty, 7}, {Mixed, 1}, {Empty, 1485},
              {Mixed, 1}, {Empty, 154}, {Full, 7}, {Mixed, 1}, {Full, 1},
              {Mixed, 1}, {Full, 1}, {Mixed, 3}, {Full, 1}, {Mixed, 1},
              {Empty, 8}, {Full, 2}, {Mixed, 2}, {Empty, 4}, {Full, 2},
              {Mixed, 1}, {Full, 1}, {Mixed, 3}, {Full, 1}, {Mixed, 3},
              {Full, 10}, {Mixed, 1}, {Full, 8}, {Mixed, 1}, {Full, 1},
              {Empty, 192}, {Full, 1}, {Mixed, 1}, {Full, 2}, {Mixed, 6},
              {Full, 1}, {Mixed, 2}, {Empty, 2}, {Mixed, 4}, {Empty, 5},
              {Full, 19}, {Mixed, 1}, {Full, 1}, {Mixed, 1}, {Full, 8},
              {Mixed, 2}, {Full, 3}, {Mixed, 1}, {Full, 2}, {Mixed, 1},
              {Empty, 1}, {Mixed, 1}, {Full, 1}, {Mixed, 1}, {Full, 1},
              {Mixed, 2}, {Empty, 2}, {Mixed, 1}, {Empty, 3}, {Mixed, 1},
              {Empty, 1}, {Mixed, 1}, {Empty, 24625}, {Mixed, 1}, {Full, 3},
              {Empty, 6140}},
             {0xf8000001, 0xf8000001, 0xfbfffbff, 0x00800000, 0x00800000,
              0xfe000000, 0xfffff3e0, 0x40100000, 0x000000a0, 0x00000200,
              0x98001020, 0x00000001, 0x20000000, 0x00000030, 0x80000000,
              0x01e00000, 0x08000000, 0x00003800, 0x00600000, 0x0000002c,
              0x00080000, 0x006fde02, 0xffffcfff, 0x7ff1ffdf, 0x00007fff,
              0x7fffffff, 0xfffbf3bf, 0xffffbfff, 0xffff0e00, 0x07ffffff,
              0x0000007f, 0x000007ff, 0xffcfffff, 0xff3fffff, 0xe3ffffff,
              0x0003fdff, 0x0000f000, 0x00000007, 0x0fff0000, 0xffffff5f,
              0xf0ff0001, 0x18000000, 0x00000001, 0x18000000, 0xffff0000,
              0x0000000f, 0x80000000, 0x0000ffff, 0xff000000, 0x00000003,
              0x00000700, 0x03ff0000, 0x00004000, 0x00008000, 0x08000000,
              0xc0000000, 0x03ff0000, 0xffff0000, 0xfff7ffff, 0x00000f7f,
              0x80000000, 0xfffffffe, 0xf8000001, 0xf8000001, 0x0001003f,
              0xc0000000, 0x3e007f7f, 0xffffff87, 0xff8fffff, 0x0fff0000,
              0xffff0000, 0x1fffffff, 0x0ffffffe, 0x0000000f, 0x003fffff,
              0xfffffe7f, 0x07fffc7f, 0xfffff018, 0xffffc3ff, 0x000001ff,
              0x007fffff, 0x0003ffff, 0xffdfffff, 0xdfffffff, 0xebffde64,
              0xffffffef, 0xdfdfe7bf, 0x7bffffff, 0xfffdfc5f, 0xffffff3f,
              0xffffcfff, 0xffff0fff, 0x000fffff, 0xfffe7fff, 0xfffefffe,
              0x003fffff, 0xffff1fff, 0xffff7fff, 0xffff0fff, 0x07ffffff,
              0xffffffc0, 0xffff0006, 0x07ffffff, 0x000301ff, 0xfbffffff,
              0xffffffef, 0x0001ffff, 0x000f1fff, 0x000fffff, 0x001fffff,
              0xffff0fff, 0x03ff00ff, 0xffff00ff, 0x00003fff, 0x01ff0000,
              0x0000001f, 0x00000001, 0x00000002}};
        /** Code Point Ranges for Zzzz
        [888, 889], [896, 899], [907, 907], [909, 909], [930, 930],
        [1328, 1328], [1367, 1368], [1376, 1376], [1416, 1416],
        [1419, 1420], [1424, 1424], [1480, 1487], [1515, 1519],
        [1525, 1535], [1565, 1565], [1806, 1806], [1867, 1868],
        [1970, 1983], [2043, 2047], [2094, 2095], [2111, 2111],
        [2140, 2141], [2143, 2207], [2229, 2274], [2436, 2436],
        [2445, 2446], [2449, 2450], [2473, 2473], [2481, 2481],
        [2483, 2485], [2490, 2491], [2501, 2502], [2505, 2506],
        [2511, 2518], [2520, 2523], [2526, 2526], [2532, 2533],
        [2556, 2560], [2564, 2564], [2571, 2574], [2577, 2578],
        [2601, 2601], [2609, 2609], [2612, 2612], [2615, 2615],
        [2618, 2619], [2621, 2621], [2627, 2630], [2633, 2634],
        [2638, 2640], [2642, 2648], [2653, 2653], [2655, 2661],
        [2678, 2688], [2692, 2692], [2702, 2702], [2706, 2706],
        [2729, 2729], [2737, 2737], [2740, 2740], [2746, 2747],
        [2758, 2758], [2762, 2762], [2766, 2767], [2769, 2783],
        [2788, 2789], [2802, 2808], [2810, 2816], [2820, 2820],
        [2829, 2830], [2833, 2834], [2857, 2857], [2865, 2865],
        [2868, 2868], [2874, 2875], [2885, 2886], [2889, 2890],
        [2894, 2901], [2904, 2907], [2910, 2910], [2916, 2917],
        [2936, 2945], [2948, 2948], [2955, 2957], [2961, 2961],
        [2966, 2968], [2971, 2971], [2973, 2973], [2976, 2978],
        [2981, 2983], [2987, 2989], [3002, 3005], [3011, 3013],
        [3017, 3017], [3022, 3023], [3025, 3030], [3032, 3045],
        [3067, 3071], [3076, 3076], [3085, 3085], [3089, 3089],
        [3113, 3113], [3130, 3132], [3141, 3141], [3145, 3145],
        [3150, 3156], [3159, 3159], [3163, 3167], [3172, 3173],
        [3184, 3191], [3200, 3200], [3204, 3204], [3213, 3213],
        [3217, 3217], [3241, 3241], [3252, 3252], [3258, 3259],
        [3269, 3269], [3273, 3273], [3278, 3284], [3287, 3293],
        [3295, 3295], [3300, 3301], [3312, 3312], [3315, 3328],
        [3332, 3332], [3341, 3341], [3345, 3345], [3387, 3388],
        [3397, 3397], [3401, 3401], [3407, 3414], [3416, 3422],
        [3428, 3429], [3446, 3448], [3456, 3457], [3460, 3460],
        [3479, 3481], [3506, 3506], [3516, 3516], [3518, 3519],
        [3527, 3529], [3531, 3534], [3541, 3541], [3543, 3543],
        [3552, 3557], [3568, 3569], [3573, 3584], [3643, 3646],
        [3676, 3712], [3715, 3715], [3717, 3718], [3721, 3721],
        [3723, 3724], [3726, 3731], [3736, 3736], [3744, 3744],
        [3748, 3748], [3750, 3750], [3752, 3753], [3756, 3756],
        [3770, 3770], [3774, 3775], [3781, 3781], [3783, 3783],
        [3790, 3791], [3802, 3803], [3808, 3839], [3912, 3912],
        [3949, 3952], [3992, 3992], [4029, 4029], [4045, 4045],
        [4059, 4095], [4294, 4294], [4296, 4300], [4302, 4303],
        [4681, 4681], [4686, 4687], [4695, 4695], [4697, 4697],
        [4702, 4703], [4745, 4745], [4750, 4751], [4785, 4785],
        [4790, 4791], [4799, 4799], [4801, 4801], [4806, 4807],
        [4823, 4823], [4881, 4881], [4886, 4887], [4955, 4956],
        [4989, 4991], [5018, 5023], [5110, 5111], [5118, 5119],
        [5789, 5791], [5881, 5887], [5901, 5901], [5909, 5919],
        [5943, 5951], [5972, 5983], [5997, 5997], [6001, 6001],
        [6004, 6015], [6110, 6111], [6122, 6127], [6138, 6143],
        [6159, 6159], [6170, 6175], [6264, 6271], [6315, 6319],
        [6390, 6399], [6431, 6431], [6444, 6447], [6460, 6463],
        [6465, 6467], [6510, 6511], [6517, 6527], [6572, 6575],
        [6602, 6607], [6619, 6621], [6684, 6685], [6751, 6751],
        [6781, 6782], [6794, 6799], [6810, 6815], [6830, 6831],
        [6847, 6911], [6988, 6991], [7037, 7039], [7156, 7163],
        [7224, 7226], [7242, 7244], [7296, 7359], [7368, 7375],
        [7415, 7415], [7418, 7423], [7670, 7675], [7958, 7959],
        [7966, 7967], [8006, 8007], [8014, 8015], [8024, 8024],
        [8026, 8026], [8028, 8028], [8030, 8030], [8062, 8063],
        [8117, 8117], [8133, 8133], [8148, 8149], [8156, 8156],
        [8176, 8177], [8181, 8181], [8191, 8191], [8293, 8293],
        [8306, 8307], [8335, 8335], [8349, 8351], [8383, 8399],
        [8433, 8447], [8588, 8591], [9211, 9215], [9255, 9279],
        [9291, 9311], [11124, 11125], [11158, 11159], [11194, 11196],
        [11209, 11209], [11218, 11243], [11248, 11263], [11311, 11311],
        [11359, 11359], [11508, 11512], [11558, 11558], [11560, 11564],
        [11566, 11567], [11624, 11630], [11633, 11646], [11671, 11679],
        [11687, 11687], [11695, 11695], [11703, 11703], [11711, 11711],
        [11719, 11719], [11727, 11727], [11735, 11735], [11743, 11743],
        [11843, 11903], [11930, 11930], [12020, 12031], [12246, 12271],
        [12284, 12287], [12352, 12352], [12439, 12440], [12544, 12548],
        [12590, 12592], [12687, 12687], [12731, 12735], [12772, 12783],
        [12831, 12831], [13055, 13055], [19894, 19903], [40918, 40959],
        [42125, 42127], [42183, 42191], [42540, 42559], [42744, 42751],
        [42926, 42927], [42936, 42998], [43052, 43055], [43066, 43071],
        [43128, 43135], [43205, 43213], [43226, 43231], [43262, 43263],
        [43348, 43358], [43389, 43391], [43470, 43470], [43482, 43485],
        [43519, 43519], [43575, 43583], [43598, 43599], [43610, 43611],
        [43715, 43738], [43767, 43776], [43783, 43784], [43791, 43792],
        [43799, 43807], [43815, 43815], [43823, 43823], [43878, 43887],
        [44014, 44015], [44026, 44031], [55204, 55215], [55239, 55242],
        [55292, 63743], [64110, 64111], [64218, 64255], [64263, 64274],
        [64280, 64284], [64311, 64311], [64317, 64317], [64319, 64319],
        [64322, 64322], [64325, 64325], [64450, 64466], [64832, 64847],
        [64912, 64913], [64968, 65007], [65022, 65023], [65050, 65055],
        [65107, 65107], [65127, 65127], [65132, 65135], [65141, 65141],
        [65277, 65278], [65280, 65280], [65471, 65473], [65480, 65481],
        [65488, 65489], [65496, 65497], [65501, 65503], [65511, 65511],
        [65519, 65528], [65534, 65535], [65548, 65548], [65575, 65575],
        [65595, 65595], [65598, 65598], [65614, 65615], [65630, 65663],
        [65787, 65791], [65795, 65798], [65844, 65846], [65933, 65935],
        [65948, 65951], [65953, 65999], [66046, 66175], [66205, 66207],
        [66257, 66271], [66300, 66303], [66340, 66351], [66379, 66383],
        [66427, 66431], [66462, 66462], [66500, 66503], [66518, 66559],
        [66718, 66719], [66730, 66815], [66856, 66863], [66916, 66926],
        [66928, 67071], [67383, 67391], [67414, 67423], [67432, 67583],
        [67590, 67591], [67593, 67593], [67638, 67638], [67641, 67643],
        [67645, 67646], [67670, 67670], [67743, 67750], [67760, 67807],
        [67827, 67827], [67830, 67834], [67868, 67870], [67898, 67902],
        [67904, 67967], [68024, 68027], [68048, 68049], [68100, 68100],
        [68103, 68107], [68116, 68116], [68120, 68120], [68148, 68151],
        [68155, 68158], [68168, 68175], [68185, 68191], [68256, 68287],
        [68327, 68330], [68343, 68351], [68406, 68408], [68438, 68439],
        [68467, 68471], [68498, 68504], [68509, 68520], [68528, 68607],
        [68681, 68735], [68787, 68799], [68851, 68857], [68864, 69215],
        [69247, 69631], [69710, 69713], [69744, 69758], [69826, 69839],
        [69865, 69871], [69882, 69887], [69941, 69941], [69956, 69967],
        [70007, 70015], [70094, 70095], [70112, 70112], [70133, 70143],
        [70162, 70162], [70206, 70271], [70279, 70279], [70281, 70281],
        [70286, 70286], [70302, 70302], [70314, 70319], [70379, 70383],
        [70394, 70399], [70404, 70404], [70413, 70414], [70417, 70418],
        [70441, 70441], [70449, 70449], [70452, 70452], [70458, 70459],
        [70469, 70470], [70473, 70474], [70478, 70479], [70481, 70486],
        [70488, 70492], [70500, 70501], [70509, 70511], [70517, 70783],
        [70856, 70863], [70874, 71039], [71094, 71095], [71134, 71167],
        [71237, 71247], [71258, 71295], [71352, 71359], [71370, 71423],
        [71450, 71452], [71468, 71471], [71488, 71839], [71923, 71934],
        [71936, 72383], [72441, 73727], [74650, 74751], [74863, 74863],
        [74869, 74879], [75076, 77823], [78895, 82943], [83527, 92159],
        [92729, 92735], [92767, 92767], [92778, 92781], [92784, 92879],
        [92910, 92911], [92918, 92927], [92998, 93007], [93018, 93018],
        [93026, 93026], [93048, 93052], [93072, 93951], [94021, 94031],
        [94079, 94094], [94112, 110591], [110594, 113663], [113771, 113775],
        [113789, 113791], [113801, 113807], [113818, 113819],
        [113828, 118783], [119030, 119039], [119079, 119080],
        [119273, 119295], [119366, 119551], [119639, 119647],
        [119666, 119807], [119893, 119893], [119965, 119965],
        [119968, 119969], [119971, 119972], [119975, 119976],
        [119981, 119981], [119994, 119994], [119996, 119996],
        [120004, 120004], [120070, 120070], [120075, 120076],
        [120085, 120085], [120093, 120093], [120122, 120122],
        [120127, 120127], [120133, 120133], [120135, 120137],
        [120145, 120145], [120486, 120487], [120780, 120781],
        [121484, 121498], [121504, 121504], [121520, 124927],
        [125125, 125126], [125143, 126463], [126468, 126468],
        [126496, 126496], [126499, 126499], [126501, 126502],
        [126504, 126504], [126515, 126515], [126520, 126520],
        [126522, 126522], [126524, 126529], [126531, 126534],
        [126536, 126536], [126538, 126538], [126540, 126540],
        [126544, 126544], [126547, 126547], [126549, 126550],
        [126552, 126552], [126554, 126554], [126556, 126556],
        [126558, 126558], [126560, 126560], [126563, 126563],
        [126565, 126566], [126571, 126571], [126579, 126579],
        [126584, 126584], [126589, 126589], [126591, 126591],
        [126602, 126602], [126620, 126624], [126628, 126628],
        [126634, 126634], [126652, 126703], [126706, 126975],
        [127020, 127023], [127124, 127135], [127151, 127152],
        [127168, 127168], [127184, 127184], [127222, 127231],
        [127245, 127247], [127279, 127279], [127340, 127343],
        [127387, 127461], [127491, 127503], [127547, 127551],
        [127561, 127567], [127570, 127743], [128378, 128378],
        [128420, 128420], [128721, 128735], [128749, 128751],
        [128756, 128767], [128884, 128895], [128981, 129023],
        [129036, 129039], [129096, 129103], [129114, 129119],
        [129160, 129167], [129198, 129295], [129305, 129407],
        [129413, 129471], [129473, 131071], [173783, 173823],
        [177973, 177983], [178206, 178207], [183970, 194559],
        [195102, 917504], [917506, 917535], [917632, 917759],
        [918000, 1114111]**/
        const UnicodeSet zzzz_Ext 
            {{{Empty, 27}, {Mixed, 3}, {Empty, 11}, {Mixed, 4}, {Empty, 1},
              {Mixed, 3}, {Empty, 7}, {Mixed, 1}, {Empty, 1}, {Mixed, 1},
              {Empty, 2}, {Mixed, 1}, {Empty, 1}, {Mixed, 1}, {Empty, 1},
              {Mixed, 2}, {Full, 2}, {Mixed, 1}, {Full, 1}, {Mixed, 1},
              {Empty, 4}, {Mixed, 39}, {Full, 1}, {Mixed, 3}, {Full, 1},
              {Empty, 2}, {Mixed, 5}, {Full, 1}, {Empty, 6}, {Mixed, 1},
              {Empty, 11}, {Mixed, 1}, {Empty, 1}, {Mixed, 3}, {Empty, 1},
              {Mixed, 1}, {Empty, 1}, {Mixed, 3}, {Empty, 2}, {Mixed, 1},
              {Empty, 20}, {Mixed, 1}, {Empty, 2}, {Mixed, 5}, {Empty, 2},
              {Mixed, 3}, {Empty, 2}, {Mixed, 1}, {Empty, 1}, {Mixed, 1},
              {Empty, 1}, {Mixed, 5}, {Empty, 1}, {Mixed, 2}, {Empty, 1},
              {Mixed, 1}, {Empty, 1}, {Mixed, 4}, {Full, 2}, {Empty, 2},
              {Mixed, 2}, {Empty, 3}, {Mixed, 1}, {Empty, 1}, {Mixed, 2},
              {Empty, 1}, {Full, 2}, {Mixed, 2}, {Empty, 7}, {Mixed, 1},
              {Empty, 8}, {Mixed, 1}, {Empty, 1}, {Mixed, 2}, {Empty, 1},
              {Mixed, 3}, {Empty, 3}, {Mixed, 5}, {Empty, 4}, {Mixed, 1},
              {Empty, 18}, {Mixed, 1}, {Empty, 1}, {Mixed, 2}, {Empty, 56},
              {Mixed, 5}, {Empty, 1}, {Mixed, 2}, {Empty, 4}, {Mixed, 1},
              {Empty, 1}, {Mixed, 1}, {Empty, 1}, {Mixed, 4}, {Empty, 3},
              {Mixed, 1}, {Full, 1}, {Mixed, 1}, {Empty, 2}, {Mixed, 1},
              {Empty, 6}, {Mixed, 2}, {Empty, 2}, {Mixed, 1}, {Empty, 1},
              {Mixed, 1}, {Empty, 3}, {Mixed, 2}, {Empty, 2}, {Mixed, 2},
              {Empty, 1}, {Mixed, 2}, {Empty, 6}, {Mixed, 1}, {Empty, 213},
              {Mixed, 1}, {Empty, 656}, {Mixed, 1}, {Full, 1}, {Empty, 36},
              {Mixed, 1}, {Empty, 1}, {Mixed, 1}, {Empty, 10}, {Mixed, 1},
              {Empty, 5}, {Mixed, 1}, {Empty, 5}, {Mixed, 1}, {Full, 1},
              {Mixed, 1}, {Empty, 1}, {Mixed, 1}, {Empty, 1}, {Mixed, 1},
              {Empty, 2}, {Mixed, 2}, {Empty, 2}, {Mixed, 2}, {Empty, 2},
              {Mixed, 2}, {Empty, 1}, {Mixed, 2}, {Empty, 3}, {Mixed, 4},
              {Empty, 1}, {Mixed, 1}, {Empty, 3}, {Mixed, 1}, {Empty, 349},
              {Mixed, 3}, {Full, 264}, {Empty, 11}, {Mixed, 1}, {Empty, 2},
              {Mixed, 1}, {Full, 1}, {Mixed, 3}, {Empty, 3}, {Mixed, 1},
              {Empty, 11}, {Mixed, 1}, {Empty, 1}, {Mixed, 1}, {Empty, 1},
              {Mixed, 3}, {Empty, 1}, {Mixed, 2}, {Empty, 3}, {Mixed, 2},
              {Empty, 4}, {Mixed, 6}, {Full, 1}, {Empty, 3}, {Mixed, 3},
              {Empty, 2}, {Mixed, 4}, {Full, 4}, {Mixed, 1}, {Empty, 1},
              {Mixed, 2}, {Empty, 1}, {Mixed, 4}, {Empty, 1}, {Mixed, 1},
              {Full, 1}, {Empty, 4}, {Mixed, 2}, {Full, 2}, {Empty, 1},
              {Mixed, 1}, {Empty, 1}, {Mixed, 1}, {Full, 4}, {Empty, 9},
              {Mixed, 3}, {Full, 4}, {Mixed, 3}, {Empty, 1}, {Mixed, 2},
              {Full, 1}, {Mixed, 3}, {Full, 2}, {Empty, 1}, {Mixed, 2},
              {Empty, 1}, {Mixed, 3}, {Empty, 2}, {Full, 1}, {Empty, 1},
              {Mixed, 1}, {Empty, 1}, {Mixed, 5}, {Full, 2}, {Empty, 2},
              {Mixed, 1}, {Full, 1}, {Empty, 1}, {Mixed, 1}, {Empty, 1},
              {Mixed, 1}, {Full, 11}, {Mixed, 1}, {Full, 12}, {Empty, 2},
              {Mixed, 2}, {Empty, 2}, {Mixed, 2}, {Empty, 1}, {Mixed, 3},
              {Empty, 2}, {Mixed, 4}, {Full, 2}, {Mixed, 2}, {Empty, 1},
              {Mixed, 5}, {Full, 8}, {Empty, 2}, {Mixed, 1}, {Full, 5},
              {Empty, 1}, {Mixed, 2}, {Full, 1}, {Empty, 2}, {Mixed, 1},
              {Full, 1}, {Empty, 1}, {Mixed, 2}, {Full, 1}, {Mixed, 2},
              {Full, 11}, {Empty, 2}, {Mixed, 1}, {Full, 14}, {Empty, 1},
              {Mixed, 1}, {Full, 40}, {Empty, 28}, {Mixed, 1}, {Full, 3},
              {Empty, 3}, {Mixed, 1}, {Empty, 6}, {Mixed, 1}, {Full, 85},
              {Empty, 33}, {Mixed, 1}, {Full, 126}, {Empty, 18}, {Mixed, 1},
              {Full, 269}, {Empty, 17}, {Mixed, 3}, {Full, 2}, {Mixed, 2},
              {Empty, 2}, {Mixed, 3}, {Full, 27}, {Empty, 2}, {Mixed, 3},
              {Full, 515}, {Mixed, 1}, {Full, 95}, {Empty, 3}, {Mixed, 3},
              {Full, 154}, {Empty, 7}, {Mixed, 1}, {Empty, 1}, {Mixed, 1},
              {Empty, 5}, {Mixed, 1}, {Empty, 2}, {Mixed, 1}, {Full, 5},
              {Empty, 2}, {Mixed, 2}, {Full, 4}, {Empty, 2}, {Mixed, 1},
              {Empty, 1}, {Mixed, 3}, {Empty, 1}, {Mixed, 3}, {Empty, 10},
              {Mixed, 1}, {Empty, 8}, {Mixed, 1}, {Empty, 21}, {Mixed, 2},
              {Full, 106}, {Empty, 6}, {Mixed, 1}, {Full, 41}, {Mixed, 6},
              {Full, 1}, {Mixed, 1}, {Full, 8}, {Empty, 1}, {Mixed, 1},
              {Empty, 2}, {Mixed, 6}, {Empty, 1}, {Mixed, 2}, {Full, 2},
              {Mixed, 4}, {Full, 5}, {Empty, 19}, {Mixed, 1}, {Empty, 1},
              {Mixed, 1}, {Empty, 8}, {Mixed, 2}, {Empty, 3}, {Mixed, 1},
              {Empty, 2}, {Mixed, 1}, {Full, 1}, {Mixed, 1}, {Empty, 1},
              {Mixed, 1}, {Empty, 1}, {Mixed, 2}, {Full, 2}, {Mixed, 1},
              {Full, 3}, {Mixed, 1}, {Full, 1}, {Mixed, 1}, {Full, 49},
              {Empty, 1334}, {Mixed, 1}, {Full, 1}, {Empty, 129},
              {Mixed, 1}, {Empty, 6}, {Mixed, 1}, {Empty, 180}, {Mixed, 1},
              {Full, 330}, {Empty, 16}, {Mixed, 1}, {Full, 22575},
              {Mixed, 1}, {Empty, 3}, {Full, 4}, {Empty, 7}, {Mixed, 1},
              {Full, 6128}},
             {0x03000000, 0x0000280f, 0x00000004, 0x00010000, 0x01800000,
              0x00000001, 0x00011900, 0x0000ff00, 0xffe0f800, 0x20000000,
              0x00004000, 0x00001800, 0xfffc0000, 0xf8000000, 0x8000c000,
              0xb0000000, 0xffe00000, 0x00000007, 0x00066010, 0x0c3a0200,
              0x4f7f8660, 0xf0000030, 0x00067811, 0x2c920200, 0xa1fdc678,
              0xffc0003f, 0x00044011, 0x0c120200, 0xfffec440, 0xfdfc0030,
              0x00066011, 0x0c120200, 0x4f3fc660, 0xff000030, 0x29c23813,
              0x3c0038e7, 0xff7ec238, 0xf800003f, 0x00022010, 0x1c000200,
              0xf89fc220, 0x00ff0030, 0x00022011, 0x0c100200, 0xbf9fc220,
              0xfff90030, 0x00022011, 0x18000000, 0x7f7f8220, 0x01c00030,
              0x03800013, 0xd0040000, 0x00a07b80, 0xffe3003f, 0x00000001,
              0x78000000, 0xf0000000, 0x010fda69, 0xc4001351, 0x0c00c0a0,
              0x00000100, 0x0001e000, 0x01000000, 0x20000000, 0xf8002000,
              0x0000df40, 0xc280c200, 0x0000c200, 0x80c20000, 0x008000c2,
              0x00c20000, 0x18000000, 0xe0000000, 0xfc000000, 0xc0c00000,
              0xe0000000, 0xfe000000, 0xffe02000, 0xff800000, 0xfff00000,
              0xfff22000, 0xc0000000, 0xfc00fc00, 0xfc008000, 0xff000000,
              0x0000f800, 0xffc00000, 0x80000000, 0xf000f000, 0x0000000e,
              0xffe0c000, 0x0000f000, 0x3800fc00, 0x30000000, 0x80000000,
              0x60000000, 0xfc00fc00, 0x8000c000, 0x0000f000, 0xe0000000,
              0x0ff00000, 0x07000000, 0x00001c00, 0x0000ff00, 0xfc800000,
              0x0fc00000, 0xc0c00000, 0x5500c0c0, 0xc0000000, 0x00200000,
              0x10300020, 0x80230000, 0x000c0020, 0xe0008000, 0x80000000,
              0x0000ffff, 0xfffe0000, 0x0000f000, 0xf8000000, 0xffffff80,
              0xfffff800, 0x00300000, 0x00c00000, 0x1c000000, 0xfffc0200,
              0xffff0fff, 0x00008000, 0x80000000, 0x01f00000, 0x0000df40,
              0x7ffe7f00, 0xff800000, 0x80808080, 0x80808080, 0xfffffff8,
              0x04000000, 0xfff00000, 0xffc00000, 0xf000ffff, 0x00000001,
              0x01800000, 0x0000001f, 0x0001c000, 0x00008000, 0xf8000000,
              0x0000fff0, 0x80000000, 0x80000000, 0xffc00000, 0xffc00000,
              0x0000e000, 0x0000ff80, 0xfffff000, 0xff000000, 0xff00c000,
              0x007fffff, 0xfc00f000, 0xff000000, 0xfc003fe0, 0xc0000000,
              0x7ff00000, 0xe0000000, 0x3c004000, 0x80000000, 0xff800000,
              0x0c00c000, 0x07fffff8, 0xff800000, 0xff818181, 0x00008080,
              0x0000ffc0, 0xfc00c000, 0x0000fff0, 0x00000780, 0xf0000000,
              0x0000c000, 0xfc000000, 0x1f07ff80, 0xa0800000, 0x00000024,
              0x0007fffc, 0x0000ffff, 0x00030000, 0xffffff00, 0xc000ffff,
              0xfc000000, 0x00080000, 0x0020f080, 0x60000000, 0x00000001,
              0x80000000, 0xe3030303, 0xc1ff8080, 0x00001000, 0x48000080,
              0xc000c000, 0xf8000000, 0x00000078, 0x00700000, 0xf000e000,
              0xfffffffe, 0x0000ffff, 0xc0000000, 0xe0000000, 0xfffe0000,
              0xf0000000, 0x0000fff0, 0x0000f800, 0xf8000000, 0x40000000,
              0xffc000f0, 0xc0000000, 0xfffffc00, 0x0000ff00, 0xffff7ff0,
              0xff800000, 0xffc00000, 0xffffff00, 0x000002c0, 0x6e400000,
              0x00400000, 0x80000000, 0xffff007f, 0x07c80000, 0x70000000,
              0x7c000000, 0x0f000000, 0x00030000, 0x01100f90, 0x78f00000,
              0xfe00ff00, 0xff800780, 0x01c00000, 0x00c00000, 0x00f80000,
              0xe1fc0000, 0xffff01ff, 0xfffffe00, 0xfff80000, 0x03f80000,
              0x80000000, 0x0003c000, 0x7fff0000, 0x0000fffc, 0xfc00fe00,
              0x00200000, 0x0000fff0, 0xff800000, 0x0000c000, 0xffe00001,
              0x00040000, 0xc0000000, 0x40004280, 0x0000fc00, 0xfc00f800,
              0x00066010, 0x0c120200, 0x1f7ec660, 0xffe0e030, 0xfc00ff00,
              0x00c00000, 0xc0000000, 0xfc00ffe0, 0xff000000, 0xfffffc00,
              0x1c000000, 0x0000f000, 0x7ff80000, 0xfe000000, 0xfc000000,
              0xffe08000, 0xfffffff0, 0xffff8000, 0xffffff80, 0xfe000000,
              0x80000000, 0xffff3c00, 0x0000ffff, 0xffc0c000, 0x0400ffc0,
              0x1f000004, 0xffff0000, 0x0000ffe0, 0x80000000, 0x00007fff,
              0xfffffffc, 0xe000f800, 0x0c00fe00, 0xfffffff0, 0xffc00000,
              0x00000180, 0xfffffe00, 0xffffffc0, 0xff800000, 0xfffc0000,
              0x00200000, 0x20000000, 0x1400219b, 0x00000010, 0x20201840,
              0x84000000, 0x000203a0, 0x000000c0, 0x00003000, 0x07fff000,
              0xffff0001, 0xff800060, 0x00000010, 0xf5080169, 0x5569157b,
              0xa1080869, 0xf0000400, 0xf0000411, 0xfffcffff, 0x0000f000,
              0xfff00000, 0x00018000, 0x00010001, 0xffc00000, 0x0000e000,
              0x00008000, 0x0000f000, 0xf8000000, 0x0000003f, 0x0000fff8,
              0xf8000000, 0xfffcfe00, 0x04000000, 0x00000010, 0xfffe0000,
              0xfff0e000, 0xfff00000, 0xffe00000, 0x0000f000, 0xfc00ff00,
              0x0000ff00, 0xffffc000, 0xfe00ffff, 0xffffffe0, 0xfffffffe,
              0xff800000, 0xffe00000, 0xc0000000, 0xfffffffc, 0xc0000000,
              0xfffffffd, 0xffff0000}};
        static ExtensionPropertyObject property_object
       {scx,
        UCD::sc,
       {&aghb_Ext, &ahom_Ext, &arab_Ext, &armi_Ext, &armn_Ext, &avst_Ext,
        &bali_Ext, &bamu_Ext, &bass_Ext, &batk_Ext, &beng_Ext, &bopo_Ext,
        &brah_Ext, &brai_Ext, &bugi_Ext, &buhd_Ext, &cakm_Ext, &cans_Ext,
        &cari_Ext, &cham_Ext, &cher_Ext, &copt_Ext, &cprt_Ext, &cyrl_Ext,
        &deva_Ext, &dsrt_Ext, &dupl_Ext, &egyp_Ext, &elba_Ext, &ethi_Ext,
        &geor_Ext, &glag_Ext, &goth_Ext, &gran_Ext, &grek_Ext, &gujr_Ext,
        &guru_Ext, &hang_Ext, &hani_Ext, &hano_Ext, &hatr_Ext, &hebr_Ext,
        &hira_Ext, &hluw_Ext, &hmng_Ext, &hrkt_Ext, &hung_Ext, &ital_Ext,
        &java_Ext, &kali_Ext, &kana_Ext, &khar_Ext, &khmr_Ext, &khoj_Ext,
        &knda_Ext, &kthi_Ext, &lana_Ext, &laoo_Ext, &latn_Ext, &lepc_Ext,
        &limb_Ext, &lina_Ext, &linb_Ext, &lisu_Ext, &lyci_Ext, &lydi_Ext,
        &mahj_Ext, &mand_Ext, &mani_Ext, &mend_Ext, &merc_Ext, &mero_Ext,
        &mlym_Ext, &modi_Ext, &mong_Ext, &mroo_Ext, &mtei_Ext, &mult_Ext,
        &mymr_Ext, &narb_Ext, &nbat_Ext, &nkoo_Ext, &ogam_Ext, &olck_Ext,
        &orkh_Ext, &orya_Ext, &osma_Ext, &palm_Ext, &pauc_Ext, &perm_Ext,
        &phag_Ext, &phli_Ext, &phlp_Ext, &phnx_Ext, &plrd_Ext, &prti_Ext,
        &rjng_Ext, &runr_Ext, &samr_Ext, &sarb_Ext, &saur_Ext, &sgnw_Ext,
        &shaw_Ext, &shrd_Ext, &sidd_Ext, &sind_Ext, &sinh_Ext, &sora_Ext,
        &sund_Ext, &sylo_Ext, &syrc_Ext, &tagb_Ext, &takr_Ext, &tale_Ext,
        &talu_Ext, &taml_Ext, &tavt_Ext, &telu_Ext, &tfng_Ext, &tglg_Ext,
        &thaa_Ext, &thai_Ext, &tibt_Ext, &tirh_Ext, &ugar_Ext, &vaii_Ext,
        &wara_Ext, &xpeo_Ext, &xsux_Ext, &yiii_Ext, &zinh_Ext, &zyyy_Ext,
        &zzzz_Ext
        }};
    }
}

#endif
