#ifndef PROPERTYOBJECTTABLE_H
#define PROPERTYOBJECTTABLE_H
/*
 *  Copyright (c) 2021 International Characters, Inc.
 *  This software is licensed to the public under the Open Software License 3.0.
 *  icgrep is a trademark of International Characters, Inc.
 *
 *  This file is generated by UCD_properties.py - manual edits may be lost.
 */

#include "PropertyAliases.h"
#include <unicode/data/PropertyObjects.h>

namespace UCD {
PropertyObject * get_NV_PropertyObject();
PropertyObject * get_CF_PropertyObject();
PropertyObject * get_DM_PropertyObject();
PropertyObject * get_FC_NFKC_PropertyObject();
PropertyObject * get_LC_PropertyObject();
PropertyObject * get_NFKC_CF_PropertyObject();
PropertyObject * get_SCF_PropertyObject();
PropertyObject * get_SLC_PropertyObject();
PropertyObject * get_STC_PropertyObject();
PropertyObject * get_SUC_PropertyObject();
PropertyObject * get_TC_PropertyObject();
PropertyObject * get_UC_PropertyObject();
PropertyObject * get_BMG_PropertyObject();
PropertyObject * get_BPB_PropertyObject();
PropertyObject * get_ISC_PropertyObject();
PropertyObject * get_JSN_PropertyObject();
PropertyObject * get_NA_PropertyObject();
PropertyObject * get_NA1_PropertyObject();
PropertyObject * get_NAME_ALIAS_PropertyObject();
PropertyObject * get_SCX_PropertyObject();
PropertyObject * get_AGE_PropertyObject();
PropertyObject * get_BLK_PropertyObject();
PropertyObject * get_SC_PropertyObject();
PropertyObject * get_BC_PropertyObject();
PropertyObject * get_BPT_PropertyObject();
PropertyObject * get_CCC_PropertyObject();
PropertyObject * get_DT_PropertyObject();
PropertyObject * get_EA_PropertyObject();
PropertyObject * get_GC_PropertyObject();
PropertyObject * get_GCB_PropertyObject();
PropertyObject * get_HST_PropertyObject();
PropertyObject * get_INPC_PropertyObject();
PropertyObject * get_INSC_PropertyObject();
PropertyObject * get_JG_PropertyObject();
PropertyObject * get_JT_PropertyObject();
PropertyObject * get_LB_PropertyObject();
PropertyObject * get_NFC_QC_PropertyObject();
PropertyObject * get_NFD_QC_PropertyObject();
PropertyObject * get_NFKC_QC_PropertyObject();
PropertyObject * get_NFKD_QC_PropertyObject();
PropertyObject * get_NT_PropertyObject();
PropertyObject * get_SB_PropertyObject();
PropertyObject * get_VO_PropertyObject();
PropertyObject * get_WB_PropertyObject();
PropertyObject * get_AHEX_PropertyObject();
PropertyObject * get_ALPHA_PropertyObject();
PropertyObject * get_BIDI_C_PropertyObject();
PropertyObject * get_BIDI_M_PropertyObject();
PropertyObject * get_CASED_PropertyObject();
PropertyObject * get_CE_PropertyObject();
PropertyObject * get_CI_PropertyObject();
PropertyObject * get_COMP_EX_PropertyObject();
PropertyObject * get_CWCF_PropertyObject();
PropertyObject * get_CWCM_PropertyObject();
PropertyObject * get_CWKCF_PropertyObject();
PropertyObject * get_CWL_PropertyObject();
PropertyObject * get_CWT_PropertyObject();
PropertyObject * get_CWU_PropertyObject();
PropertyObject * get_DASH_PropertyObject();
PropertyObject * get_DEP_PropertyObject();
PropertyObject * get_DI_PropertyObject();
PropertyObject * get_DIA_PropertyObject();
PropertyObject * get_EXT_PropertyObject();
PropertyObject * get_GR_BASE_PropertyObject();
PropertyObject * get_GR_EXT_PropertyObject();
PropertyObject * get_GR_LINK_PropertyObject();
PropertyObject * get_HEX_PropertyObject();
PropertyObject * get_HYPHEN_PropertyObject();
PropertyObject * get_IDC_PropertyObject();
PropertyObject * get_IDEO_PropertyObject();
PropertyObject * get_IDS_PropertyObject();
PropertyObject * get_IDSB_PropertyObject();
PropertyObject * get_IDST_PropertyObject();
PropertyObject * get_JOIN_C_PropertyObject();
PropertyObject * get_LOE_PropertyObject();
PropertyObject * get_LOWER_PropertyObject();
PropertyObject * get_MATH_PropertyObject();
PropertyObject * get_NCHAR_PropertyObject();
PropertyObject * get_OALPHA_PropertyObject();
PropertyObject * get_ODI_PropertyObject();
PropertyObject * get_OGR_EXT_PropertyObject();
PropertyObject * get_OIDC_PropertyObject();
PropertyObject * get_OIDS_PropertyObject();
PropertyObject * get_OLOWER_PropertyObject();
PropertyObject * get_OMATH_PropertyObject();
PropertyObject * get_OUPPER_PropertyObject();
PropertyObject * get_PAT_SYN_PropertyObject();
PropertyObject * get_PAT_WS_PropertyObject();
PropertyObject * get_PCM_PropertyObject();
PropertyObject * get_QMARK_PropertyObject();
PropertyObject * get_RADICAL_PropertyObject();
PropertyObject * get_RI_PropertyObject();
PropertyObject * get_SD_PropertyObject();
PropertyObject * get_STERM_PropertyObject();
PropertyObject * get_TERM_PropertyObject();
PropertyObject * get_UIDEO_PropertyObject();
PropertyObject * get_UPPER_PropertyObject();
PropertyObject * get_VS_PropertyObject();
PropertyObject * get_WSPACE_PropertyObject();
PropertyObject * get_XIDC_PropertyObject();
PropertyObject * get_XIDS_PropertyObject();
PropertyObject * get_XO_NFC_PropertyObject();
PropertyObject * get_XO_NFD_PropertyObject();
PropertyObject * get_XO_NFKC_PropertyObject();
PropertyObject * get_XO_NFKD_PropertyObject();
PropertyObject * get_EMOJI_PropertyObject();
PropertyObject * get_EMOJIPRESENTATION_PropertyObject();
PropertyObject * get_EMOJIMODIFIER_PropertyObject();
PropertyObject * get_EMOJIMODIFIERBASE_PropertyObject();
PropertyObject * get_EMOJICOMPONENT_PropertyObject();
PropertyObject * get_EXTENDEDPICTOGRAPHIC_PropertyObject();
PropertyObject * get_ALNUM_PropertyObject();
PropertyObject * get_XDIGIT_PropertyObject();
PropertyObject * get_BLANK_PropertyObject();
PropertyObject * get_PRINT_PropertyObject();
PropertyObject * get_WORD_PropertyObject();
PropertyObject * get_GRAPH_PropertyObject();

PropertyObject * getPropertyObject(property_t property_code);
}

#endif
