#!/bin/bash 
#
# Robert D. Cameron
#
# Usage: ./run_all test_program
# Example ./run_all ../u8u16
#
test_dir=`echo "$0" | sed "s/[^\/]*$//"`

test_program=$1
input_directory=TestFiles
output_directory=TestOutput


[ -x "$output_directory.bak" ] && rm -rf $output_directory.bak
[ -x "$output_directory" ] && mv $output_directory $output_directory.bak

mkdir $output_directory

for f in $input_directory/*
do
   tfile=`echo $f | sed "s/$input_directory\///"`
   fbase=`echo $tfile | sed "s/.lz4//"`
   $test_program $input_directory/$tfile $output_directory/$fbase
done

diff -q --exclude='.svn' ExpectedOutput TestOutput

