stages:
  - build
  - test

image: luizperes/parabix:llvm-9

build_llvm9:
  stage: build
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DBOOST_INCLUDEDIR=/home/boost_1_68_0 ..
    - make -j4

.test-default: &test-default
  stage: test
  before_script:
    - apt-get install -y python python3
  script:
    - mkdir -p build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DBOOST_INCLUDEDIR=/home/boost_1_68_0 ..
    - make -j4 check && make kernel-tests

test_llvm9:
  <<: *test-default

merge_request_llvm9:
  <<: *test-default
  rules:
    # If there is a merge request
    - if: '$CI_MERGE_REQUEST_IID'
