stages:
  - build
  - test

build_llvm8:
  stage: build
  image: luizperes/parabix:llvm-8
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j4

.test-default: &test-default
  stage: test
  image: luizperes/parabix:llvm-8
  script:
    - mkdir -p build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j4 check && make kernel-tests

test_llvm8:
  <<: *test-default

merge_request_llvm8:
  <<: *test-default
  rules:
    # If there is a merge request
    - if: '$CI_MERGE_REQUEST_IID'

test_llvm8_avx512:
  stage: test
  script:
    - mkdir -p build && cd build
    # Make sure the runner has LLVM installed on /opt/llvm/libllvm{LLVM_VERSION}
    - cmake -DCMAKE_PREFIX_PATH=/opt/llvm/libllvm8 -DCMAKE_BUILD_TYPE=Release ..
    - make -j4 check && make kernel-tests
  tags:
    - avx512

